### ISSUE TITLE
Alamofire First Request Always Fail After The App Wake Up From Screen Lock

### ISSUE THREAD

**Issue by Jayvd** [Alamofire/Alamofire#1586] opened 2016-09-21 06:41 UTC
I am using Alamofire for requesting data from my server. It works great 

But if I turn off the screen/lock the phone while my app in foreground and then unlock the phone. The first request will always fail.

Any thought on why is this happening? I am using Alamofire 2.0

**Comment by NielsKoole** [comment] 2016-09-23 15:53
I have the same issue, cannot find why this is happening.

FWIW, the is the response object the first time:
`[Request]: <NSMutableURLRequest: 0x15f594a70> { URL: https://xxxxx/1/register }
[Response]: nil
[Data]: 0 bytes
[Result]: FAILURE: Error Domain=NSURLErrorDomain Code=-1004 "Geen verbinding met de server mogelijk." UserInfo={NSUnderlyingError=0x161127d10 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x15f6e1d50 [0x1a08a8150]>{length = 16, capacity = 16, bytes = 0x100201bb80c7276a0000000000000000}, _kCFStreamErrorCodeKey=-2200, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://xxxxx/1/register, NSErrorFailingURLKey=https://xxxxx/1/register, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2200, NSLocalizedDescription=Geen verbinding met de server mogelijk.}
[Timeline]: Timeline: { "Request Start Time": 496338624.807, "Initial Response Time": 496338624.901, "Request Completed Time": 496338624.901, "Serialization Completed Time": 496338624.901, "Latency": 0.094 secs, "Request Duration": 0.094 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.094 secs }
  ▿ request : Optional<NSURLRequest>
    - Some : <NSMutableURLRequest: 0x15f594a70> { URL: https://xxxxx/1/register }
  - response : nil
  ▿ data : Optional<NSData>
    - Some : <>
  ▿ result : FAILURE: Error Domain=NSURLErrorDomain Code=-1004 "Geen verbinding met de server mogelijk." UserInfo={NSUnderlyingError=0x161127d10 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x15f6e1d50 [0x1a08a8150]>{length = 16, capacity = 16, bytes = 0x100201bb80c7276a0000000000000000}, _kCFStreamErrorCodeKey=-2200, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://xxxxx/1/register, NSErrorFailingURLKey=https://xxxxx/1/register, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2200, NSLocalizedDescription=Geen verbinding met de server mogelijk.}
  ▿ timeline : Timeline: { "Request Start Time": 496338624.807, "Initial Response Time": 496338624.901, "Request Completed Time": 496338624.901, "Serialization Completed Time": 496338624.901, "Latency": 0.094 secs, "Request Duration": 0.094 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.094 secs }
    - requestStartTime : 496338624.80719
    - initialResponseTime : 496338624.90076298
    - requestCompletedTime : 496338624.90076298
    - serializationCompletedTime : 496338624.90092599
    - latency : 0.09357297420501709
    - requestDuration : 0.09357297420501709
    - serializationDuration : 0.00016301870346069336
    - totalDuration : 0.093735992908477783 { ... }`

**Comment by cnoon** [comment] 2016-09-24 20:42
This is a duplicate of #1594. I'm going to close this issue out. Please direct all future comments to #1594.

**Closed by cnoon** 2016-09-24 20:42 UTC
Labels: duplicate
