### ISSUE TITLE
Alamofire 3.1 leak in Xcode 7.1 (iOS 8.3)

### ISSUE THREAD

**Issue by mruvim** [Alamofire/Alamofire#915] opened 2015-11-10 22:31 UTC
In Xcode 7.1 on iOS 8.3 with Alamofire 3.1 Xcode shows memory leaks for Alamofire calls. Below attached code that generates the leak and screenshot. 

        Alamofire.request(.GET, "https://httpbin.org/get", parameters: ["foo": "bar"])
            .responseJSON { response in
                switch response.result {
                case .Success(let json):
                    print(json)
                case .Failure(let error):
                    print(error)
                }
        }

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/VDXXl.png

**Comment by jshier** [comment] 2015-11-20 16:49
From what I can see here, it looks like the Swift standard library is leaking the structure it uses to check the OS version when we use `if #available` in `encode`. Can you post the project you used to reduce this issue? It would allow us to replicate it more easily and confirm my suspicions.

**Comment by cnoon** [comment] 2015-11-22 20:39
Okay @jshier, I put together a small sample app that demonstrates the leak. Unfortunately I'm having major issues with `Leaks` where I cannot see anything other than the symbol addresses on iOS 8.3. I'm definitely able to repo the leak, but I cannot tell what the leak actually is the same way that @mruvim has demonstrated. I'm wondering if you could pick this up from here? I've pushed up a small sample project making it easy to debug.

* https://github.com/cnoon/AlamofireLeakage

I'm almost certain there's a leak in the availability checks which means we just need to file a radar. But without being able to dig into this any further, I'd hesitate to file the radar myself.

**Comment by mruvim** [comment] 2015-11-25 19:21
@cnoon my test project looked identical to yours, so yes it's the same leak.

**Comment by jshier** [comment] 2015-11-28 21:41
@cnoon I've attempted to replicate the leak using multiple version of Xcode and I'm suffering from the same missing symbol issue you are. Leaks may be broken on El Capitan, because the Time instrument works fine.

In any event I think it's fine to report the issue to Apple, as any memory leak in Swift is a compiler or system library issue, and there are more than just this leak visible when you run the demo app. However, they probably won't fix the issue as it doesn't affect iOS 9.1. I'm sure a radar with with a link to this issue and the demo project would be appreciated though.

@mruvim It seems unlikely we'll be able to fix this issue directly or through a workaround, as the platform check is necessary to work around another framework bug, as noted in the code comment. We could drop the platform check and use the workaround code on all platforms but that would lead to an unacceptable performance regression on all platforms.

**Comment by cnoon** [comment] 2015-11-30 18:11
Thanks everyone for the help here. I just opened [rdar://23689364](https://openradar.appspot.com/radar?id=4980581951602688) which hopefully will bring this to Apple's attention. I'm going to go ahead and close this out @mruvim. Thanks again for reporting. 🍻

**Closed by cnoon** 2015-11-30 18:11 UTC
Labels: needs investigation, support
