### ISSUE TITLE
partial apply for DownloadRequest.Downloadable.(task(session : URLSession, adapter : RequestAdapter?, queue : DispatchQueue) throws -> URLSessionTask).(closure #1)

### ISSUE THREAD

**Issue by llKoull** [Alamofire/Alamofire#2559] opened 2018-07-27 07:32 UTC
Hello!

I have been using this library to manage my connections for a long time but for a month, more or less, I have seen an error in fabric that I can not find where it may come from.

Fabric seems to point to SessionManager.swift or something related with Request.swift but i don't know how to fix it. I have not even been able to reproduce it but I have many affected users.

I attach the log generated by fabric 😉

Thanks and best regards!

[fabric.txt](https://github.com/Alamofire/Alamofire/files/2234908/fabric.txt)

**Comment by cnoon** [comment] 2018-07-27 17:17
Thanks for the report @llKoull. 🍻

I dug through all the Alamofire logic there and I don't think there are any thread-safety issues in that section of the code. Additionally, even if you are using an adapter, that doesn't appear to be the issue because it's the following line running `queue.sync` that is the underlying issue. I'm wondering if it could be caused by an exception being thrown inside the closure which is the `URLSession` failing to create a valid data task. There are a couple reasons as to why I think that could happen.

1) The underlying `URLSession` has been invalidated.

> However, I'm very doubtful this is the actual issue. If you are actually doing something like `sessionManager.session.invalidateAndCancel()`, then this could be the problem.

2) The `URL` being used to generate the `URLRequest` is invalid.

I am pretty confident this is your actual issue. Here's a quick playground example demonstrating what's probably going on.

```swift
import Foundation

let url = URL(string: "/super/invalid/url")!
let urlRequest = URLRequest(url: url)

let urlSession = URLSession()
let task = urlSession.dataTask(with: urlRequest) // kaboom!
```

I would suggest really investigating the `AlamofireHelperrequestGETURL` API in `AlamofireHelper.swift:92` to try to pinpoint the issue. I would guess you have an invalid `URL` being built in certain cases that doesn't have proper safety around it.

I'm going to close this issue out for now, but if you find any more information that leads you to think it is an actual Alamofire issue, please comment back and we'll happily re-open. Also, if you do track down the issue, please comment back on this ticket to close the loop!

Best of luck! 🍻

**Closed by cnoon** 2018-07-27 17:17 UTC

**Comment by llKoull** [comment] 2018-07-27 22:03
Hello @cnoon !

Thanks for your answer, we are using an API that identifies the users by a cookie (that can get invalidated at any time). So the flow is that when the application starts, we perform a login requests (that returns us a valid session cookie) and, if any of the requests that the user do, returns us a 401 we should remove the cookie and perform a new login to get a new session.
When this occurs, i'm calling to these methods just before to renew the session:

```
func closeAndInvalidateSession() {
        self.removeAllCookies()
        self.alamofireInstance.invalidateSession()
        self.alamofireInstance.initializeParameters(shouldTrackConnectionChanges: true)
}

func removeAllCookies() {
        self.alamofireInstance.cleanAllCookies()
}
```

that are using those methods from my alamofireinstance wrapper:

```

func cleanAllCookies() {
        URLCache.shared.removeAllCachedResponses()
        if self.sessionManager.session.configuration.httpCookieStorage != nil {
            self.sessionManager.session.configuration.httpCookieStorage!.removeCookies(since: Date(timeIntervalSince1970: 0))
        }
}

func invalidateSession()
    {
        self.resignNotificationHandlers()
        self.sessionManager.session.getTasksWithCompletionHandler { (sessionDataTask, uploadData, downloadData) in
            sessionDataTask.forEach { $0.cancel() }
            uploadData.forEach { $0.cancel() }
            downloadData.forEach { $0.cancel() }
        }
        self.sessionManager.session.invalidateAndCancel()
    }

func initializeParameters(shouldTrackConnectionChanges: Bool)
    {
        let configuration = URLSessionConfiguration.default
        configuration.httpCookieAcceptPolicy = .onlyFromMainDocumentDomain
        configuration.httpCookieStorage = .shared
        configuration.requestCachePolicy = .reloadIgnoringLocalAndRemoteCacheData
        configuration.urlCache = nil
        
        self.sessionManager = Alamofire.SessionManager(configuration: configuration, delegate: self, serverTrustPolicyManager: nil)
        
        do{
            try reachability.startNotifier()
        }catch{
            print("could not start reachability notifier")
        }
        
        if shouldTrackConnectionChanges == true {
            self.initializeNotificationHandlers()
        }else{
            self.resignNotificationHandlers()
        }
    }
```

That was the only way i found to remove the old session (with the old cookie) and starts a new one using the new cookie received after the automatic login.

Thanks by your support! ^_^

**Comment by cnoon** [comment] 2018-07-29 19:46
Bingo! So now we know the core problem @llKoull. You are invalidating the underlying `URLSession`, but you are continuing the make requests on the invalidated session (most likely while setting up the new one) which is causing the exceptions to be thrown.

Now, as for solving this issue, you have a bunch of ways you could do so. First off, if you can track down how requests are still being executed on the invalidated session while you're setting up the new one, that should resolve the issue.

Another approach (one that I use in my own apps) would be to use an `Adapter` and `Retrier` to manage this logic for you. You shouldn't have to create a completely new `URLSession` just because your cookie changed. In order to do that, you could catch the 401s in the `Retrier`, refresh the cookie, then retry the requests that failed with the 401s. You "could" use an `Adapter` to attach the Cookie to the request, or you could continue to use the shared cookie storage like you are currently. For more info, I'd recommend reading through the [`Adapting and Retrying Requests`](
https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#adapting-and-retrying-requests) section in our README.

Cheers. 🍻

**Comment by llKoull** [comment] 2018-07-29 19:56
Hi @cnoon !

Thanks for your answer!! ;)

I'm doing just what you said, when I get a 401 I have a retrier that handles the session refresh and retries the original request, the problem is that if I don't call to my method closeAndInvalidateSession() the session doesn't get refreshed and all the following requests that the user do fail.

Which method do you use to remove the old cookie session and set the new one? I thought that it would be automatic but I didn't found the way to do it without closing the session and creating a new one :S

Regards!

**Comment by cnoon** [comment] 2018-07-30 17:07
Gotcha. You'll want to troubleshoot removing the old cookie and setting the new one. You should absolutely be able to do this without closing the current session and recreating a new one. I'm assuming you're not clearing the old one correctly or setting the new one correctly.

You could always add the cookie manually in the adapter instead. Then you'd know it was being set correctly, but that is certainly more work.

**Comment by llKoull** [comment] 2018-07-31 10:45
Yes i implemented that approach, now i'm cleaning and setting te cookie manually and it seems to work 😄 

Thanks for all your help!!

Best regards!
