### ISSUE TITLE
building success but launch app crashed , how to fix it ?

### ISSUE THREAD

**Issue by cleverliz** [Alamofire/Alamofire#1740] opened 2016-10-30 07:47 UTC
![2a90b150-b877-41ed-8ca0-a738a088331b](https://cloud.githubusercontent.com/assets/1953494/19835135/f96376a2-9eb7-11e6-8ecb-22adb8006ed1.png)

**Comment by cleverliz** [comment] 2016-10-30 07:57
swift3 xcode 8.1

**Comment by WishWei** [comment] 2016-11-08 09:50
I have same problem after update Xcode to 8.1

**Comment by jshier** [comment] 2016-11-13 00:14
Looks like an underlying issue in the Swift standard library, likely what we saw in #1686. We'll investigate and decide what to do. @cleverliz Could you provide more info? Alamofire version, optimization settings, device, etc. A full stack trace that we can use in a report to the Swift project would be great too.

**Comment by cnoon** [comment] 2016-11-13 00:45
Hi @cleverliz and @WishWei, we have been unable to reproduce this crash on our end at all. Would either of you be able to create a sample app that reproduces the issue? Without it, we don't have anything else left to investigate. I've tried debugging this in the simulator and on a device with varying optimization levels to no avail.

I don't want to submit a bug to the Swift project until we have a way to definitively reproduce it on our end first. If you could provide us with a sample project, then we'll be happy to investigate this further.

I'm going to close this issue out for now. If you provide more info, then we'll happily re-open and investigate further.

Cheers. 🍻

**Closed by cnoon** 2016-11-13 00:45 UTC
Labels: needs investigation, swift

**Comment by WishWei** [comment] 2016-11-14 09:11
I use Alamofire by cocoaPods,I  tried to add  files to project, then remove it, this worked to me.

**Comment by iGranDav** [comment] 2016-11-29 23:39
I currently having the exact same issue on Xcode 8.1 / Swift 3 using Alamofire 4.2.0 from cocoapods.

It crashes when trying to access the underlying `task` from it's `delegate`

```
/// The request sent or to be sent to the server.
open var request: URLRequest? { return task?.originalRequest }
```

Here is the underlying exception sent :
`'NSInvalidArgumentException', reason: '*** -[NSProxy doesNotRecognizeSelector:originalRequest] called!'`

**Comment by iGranDav** [comment] 2016-11-30 21:25
We final resolved the issue with our team, it was due to Crittercism SDK.

Here is the fix :
```
let configuration = CrittercismConfig()
    configuration.monitorNSURLSession = false
    configuration.monitorNSURLConnection = false
    Crittercism.enable(withAppID: "e0a640e13b9d45a5bb679bade45f1be400555300", andConfig: configuration)
```
