### ISSUE TITLE
Issue with isReachable in NetworkReachabilityManager

### ISSUE THREAD

**Issue by IvanZhouGitHub** [Alamofire/Alamofire#1105] opened 2016-03-09 09:44 UTC
I found a issue with isReachable in NetworkReachabilityManager when network condition is 100% loss.
My code :
let isReachable = NetworkReachabilityManager(host:"192.168.3.1:3000")!.isReachable
In ios8 isReachable is false
In ios9 isReachable is true
I hope you can solve my doubts.

**Comment by cnoon** [comment] 2016-03-09 15:14
Marking as a duplicate of #1086.

**Comment by cnoon** [comment] 2016-03-19 19:12
I'm going to close this issue out since it's a duplicate of #1086 @IvanZhouGitHub. Please redirect all comments to that issue instead.

Thanks! 🍻

**Closed by cnoon** 2016-03-19 19:12 UTC
Labels: bug, duplicate, reachability
