### ISSUE TITLE
AlamoFire full IPv6 support

### ISSUE THREAD

**Issue by racer1988** [Alamofire/Alamofire#1228] opened 2016-05-06 09:06 UTC
Hello,

Due to http://9to5mac.com/2016/05/04/apple-will-require-ios-app-store-apps-to-support-ipv6-only-networks-from-june-1/

I am opening this for raising a small issue, but also to ask a question.

Is alamofire fully supporting IPv6?
referencing the doc from Apple 
https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1

I haven't found any hardcoded IP address or reference to low level api apart those:

NetworkReachabilityManager.swift  
is using IPv4 only:
`AF_INET `
and
`sockaddr_in `

Apple suggest to support also IPv6 counterparts:
https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW12

If your code handles IPv4 types, make sure the IPv6 equivalents are handled too.

IPv4
IPv6
AF_INET
AF_INET6
PF_INET
PF_INET6
struct in_addr
struct in_addr6
struct sockaddr_in
struct sockaddr_in6
kDNSServiceProtocol_IPv4
kDNSServiceProtocol_IPv6

Thanks

**Comment by cnoon** [comment] 2016-05-08 23:01
Your concerns here are perfectly valid @racer1988. The problem is that Apple isn't clear on whether apps supporting iOS 8 are going to be held to these same rules. If you check out #1086, you'll see that the reachability APIs don't work correctly on iOS 8 with IPv6. Therefore, I rolled back to the IPv4 APIs for iOS 8. I can certainly undo that change, but that will break reachability for anyone running on iOS 8.

An alternative approach would be to only make the `NetworkReachabilityManager` available to iOS 9 and above, but I'd rather not do that.

I'm going to leave this issue open for now. Maybe the community can help us decide on what the best solution is here.

**Comment by cnoon** [comment] 2016-05-08 23:01
cc @kcharwood, @jshier, @kylef, @AnthonyMDev.

**Comment by dgatwood** [comment] 2016-05-09 03:21
iOS 8 didn't have NAT64 support, so any iOS 8 device on an IPv6-only network would be hopelessly crippled.  Based on that, I'm pretty sure that as long as your code uses the IPv4 APIs only when actually running on iOS 8 and earlier (i.e. run-time checks, not build-time checks), you should be fine.

**Comment by racer1988** [comment] 2016-05-09 07:52
@cnoon @dgatwood Thanks :D

if the issue is < iOS 9 why not putting the IPv6 code wrapped in 

`if #available(iOS 9, *) `

and in a else the IPv4 support for all other iOS versions?

**Comment by cnoon** [comment] 2016-05-09 14:02
That's exactly what we do now @racer1988 in the [NetworkReachabilityManager](https://github.com/Alamofire/Alamofire/blob/master/Source/NetworkReachabilityManager.swift#L123-L145).

**Comment by racer1988** [comment] 2016-05-09 14:21
AND LOL! 😫 

I did a grep and didn't see it :D

**Comment by AnthonyMDev** [comment] 2016-05-10 01:17
So if we are already checking for iOS 9, then this isn't an issue, right?

**Comment by cnoon** [comment] 2016-05-10 05:04
Unfortunately, it's just a running theory right now @AnthonyMDev...we don't have a definitive answer yet. I tend to agree with @dgatwood, but I'd much rather be certain.

**Comment by cezheng** [comment] 2016-05-14 12:50
The current implementation of Alamofire's Reachability just uses `sockaddr_in6` on iOS 9 or later. Will this cause any problem if the device happens to be connecting to a IPv4 network?

However in the [README](https://developer.apple.com/library/ios/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11) of the [Reachability sample](https://developer.apple.com/library/ios/samplecode/Reachability/Listings/Reachability_Reachability_m.html#//apple_ref/doc/uid/DTS40007324-Reachability_Reachability_m-DontLinkElementID_9), it says

```
Reachability fully supports IPv6.  More specifically, each of the APIs handles IPv6 in the following way:

...

- reachabilityForInternetConnection:  This monitors the address 0.0.0.0, which reachability treats as a special token that causes it to actually monitor the general routing status of the device, both IPv4 and IPv6.
```

and the implementation actually uses `sockaddr_in`

```objc
+ (instancetype)reachabilityForInternetConnection {
    struct sockaddr_in zeroAddress;
    bzero(&zeroAddress, sizeof(zeroAddress));
    zeroAddress.sin_len = sizeof(zeroAddress);
    zeroAddress.sin_family = AF_INET;
    return [self reachabilityWithAddress: (const struct sockaddr *) &zeroAddress];
}
```

**Comment by cnoon** [comment] 2016-05-22 17:34
Pretty sure you posted on the wrong project @cezheng.

**Comment by cezheng** [comment] 2016-05-22 17:49
@cnoon 
Why would you say that?
https://github.com/Alamofire/Alamofire/blob/master/Source/NetworkReachabilityManager.swift#L125

I just think the implementation of Alamofire's Reachability might be problematic on IPv4 only network

**Comment by cezheng** [comment] 2016-05-22 17:51
@cnoon 
Would you explain why Alamofire need to use sockaddr_in6 for iOS 9 or later, while apple's official sample of Reachability claims that 0.0.0.0 is treated as a special token?

**Comment by dooofy** [comment] 2016-05-22 19:09
I agree. Why should we adopt a potentially problematic implementation, while we already have a apple-verified implementation(which is exactly the same as Alamofire's old implementaation)? I'd rather trust apple's official sample.

**Comment by cnoon** [comment] 2016-05-22 19:20
Ah, I misunderstood your original post @cezheng. I didn't realize you were posting a code sample from the Reachability project.

**Comment by cnoon** [comment] 2016-05-22 19:24
Thanks for posting all the documentation info @cezheng. That sample code was actually updated by Apple right after this ticket was opened. We need to re-evaluate our implementation based on the new sample code and description provided by Apple. Seems like there are a few opportunities for us to improve our logic.

**Comment by cezheng** [comment] 2016-05-23 06:43
Thanks, I got it.

And also I guess the original IPv6 support change was kind of like a miscomprehension of apple's guideline.

> If your code handles IPv4 types, make sure the IPv6 equivalents are handled too.

doesn't necessarirly mean that we should handle IPv6 types only, which is the current status for iOS >= 9.

**Comment by dgatwood** [comment] 2016-05-23 07:41
Yikes. Most devices are still on IPv4-only networks, so yes, it definitely needs to support both.

**Comment by sthielen** [comment] 2016-06-05 18:01
Has anyone had any issues getting apps using Alamofire approved by Apple now that the IPv6 only restriction is in place? I submitted a cosmetic update to Apple the other day and it's being rejected because they're getting network errors. I can't reproduce the issue when I follow [Apple's instructions for setting up an IPv6 network](https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1) and our API is [set up fine for IPv6 traffic](https://ip6.nl/#!api.metooapp.io). We're only using Alamofire for networking, with no hard-coded IPs or anything like that, and none of the networking code has changed in this update from the version currently on the app store, so I'm thinking the issue might be here? I can't even reproduce the issue though, which is making it incredibly difficult to diagnose.

**Comment by cnoon** [comment] 2016-06-13 00:03
I've just opened #1308 which should bring Alamofire inline with Apple's recommendations when it comes to Reachability. I'm going to close this issue out. Please direct all future comments to #1308. Thanks for everyone's help getting to the bottom of this. We really appreciate everyone helping out here!

Cheers. 🍻

**Closed by cnoon** 2016-06-13 00:03 UTC
Labels: help wanted, needs feedback, needs investigation, reachability

**Comment by robertofrontado** [comment] 2016-07-29 20:52
@cnoon Hey man I've a question, 

I know this issue is closed but, the current version of Alamofire (v3.4.1) supports IPv6-only networks? Because Apple is rejecting my application saying that the HTTPs requests are failing.

Any idea? I'm running out of time :S

**Comment by cezheng** [comment] 2016-07-30 06:47
> Because Apple is rejecting my application saying that the HTTPs requests are failing.

This issue is only related to Reachability which is just an optional feature, and it does not seem to be related to the failing HTTPS requests. Did apple provide any more details?

**Comment by robertofrontado** [comment] 2016-07-30 07:51
This is what they told me

> We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 9.3.2 on Wi-Fi connected to an IPv6 network.
> 
> Specifically, your app returns an error message when we sign in using Facebook and or when attempting to register. 

Any idea?

**Comment by cnoon** [comment] 2016-07-31 18:55
My guess is that this has something to do with the Facebook calls. Alamofire 3.4.1 should be fully IPv6 compliant. We have multiple apps in the AppStore right now built with that exact version.

**Comment by robertofrontado** [comment] 2016-08-01 14:09
Thanks man

**Comment by ANSCoder** [comment] 2016-08-14 03:10
Same thing happened again i also did changes in Alamofire NetworkReachabilityManager as per @cnoon for IPv6 network but today again Apple rejected my app with the same issue.
=================
   Your app still still crashes on iPad and iPhone running iOS 9.3.4 connected to an IPv6 network when we:

Specifically, your app will crash after logging in.

This occurred when your app was used:

- Offline
- On Wi-Fi

**Comment by nikita-leonov** [comment] 2016-08-26 00:05
@cnoon we got application rejected by Apple for IPV6 reason. We are using 3.4.1 and we are iOS 9.0 app now. What would be you recommend set of actions?

**Comment by nikita-leonov** [comment] 2016-08-26 00:55
@cnoon it also worth to mention that previous version with 3.4.1 passed apple review, so likely they just do not this checks often. I assume this is how multiple apps passed into App Store.

**Comment by nikita-leonov** [comment] 2016-08-26 01:49
It seems that current approach works only because of mixed networks. IPV6 only network will not handle current Network Reachability approach. Apple explicitly mentioned this in their documentation  regarding 0.0.0.0 calls. Check "Connect without Preflight" section — https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW25

**Comment by cezheng** [comment] 2016-08-26 04:15
> it also worth to mention that previous version with 3.4.1 passed apple review, so likely they just do not this checks often. I assume this is how multiple apps passed into App Store.

@nikita-leonov If that's the case, you should check what changes you added in your rejected version. Currently implementation is exactly the same as apple's updated version of [Reachability Sample](https://developer.apple.com/library/ios/samplecode/Reachability/Listings/Reachability_Reachability_m.html#//apple_ref/doc/uid/DTS40007324-Reachability_Reachability_m-DontLinkElementID_9), where Apple explicitly stated 

> reachabilityForInternetConnection: This monitors the address 0.0.0.0, which reachability treats as a special token that causes it to actually monitor the general routing status of the device, both IPv4 and IPv6.

**Comment by cezheng** [comment] 2016-08-26 04:23
"Connect without Preflight" section only says it is not recommended to rely on preflight. Alamofire's ReachabilityManager is also a optional feature. If you are not using it then it has no impact on Alamofire's other features.

**Comment by kcharwood** [comment] 2016-08-26 14:32
I reviewed this code with the Eskimo at WWDC and he said it was also good. He also explained that there are all kinds of nuances with connecting to IPV6 networks that could cause a failure.

He said testing the with fake IPV6 network on your mac is NOT a good test. You need to be on a true IPV6 network. I've seen a client where we got rejected for IPV6 and could not repro the problem, but on the WWDC true IPV6 network it was easily reproducible. We tracked it down to it being a problem with one of our API servers that didn't play nice with a direct IPV6 connection. It had nothing to do with our code.

**Comment by ANSCoder** [comment] 2016-08-31 07:47
@cnoon  Thanks for the suggestion successfully approve my app 20 days before.

**Comment by nikita-leonov** [comment] 2016-08-31 17:27
@kcharwood it was likely some network disturbance that confused apple. We got our application approved afterward with close to nothing changes in a networking code. 

As for IPV6 support, I do agree that it is not only frontend problem, but also something that backend team should work on as well. We investigated our backend setup and found a couple of potential problems that need to be addressed to support IPV6 better.

**Comment by YacineVC** [comment] 2016-09-15 04:13
@nikita-leonov Hi nikita, we are having exactly the same problem. What have you changed in your network code ?
Thank you in advance

**Comment by nikita-leonov** [comment] 2016-09-15 04:17
@YacineVC nothing *facepalm* it could be that it was some other interference on an Apple side while they were doing a test, as the result they decided that our app is not IPV6 complaint. As @kcharwood  mentioned it seems that existing reachability code with 0.0.0.0 is ok from an Apple standpoint.

**Comment by YacineVC** [comment] 2016-09-15 04:27
@nikita-leonov Thank you for your reactivity ! We will see with our backend and Apple 
Finger crossed

**Comment by niennonno** [comment] 2016-09-30 10:43
I know this issue is marked closed but we faced the same issue when we are submitting an update to our app. We have Alamofire 3.4 running and iOS version is 8.0+ . our app got accepted once but now the update submission keeps getting rejected  from Apple. Our servers can handle both IPv6 and IPv4 but unfortunately we don't have an IPv6 network to test out our app with.

Do I have to change something in my NetworkReachabilityManager.swift file, like AF_INET to AF_INET6 or something? Really desperate for the answer here.

**Comment by YacineVC** [comment] 2016-09-30 12:25
@niennonno After our reject we asked a review to the App Review Submission Community. 
It has been accepted afterwards. 
As @nikita-leonov said, the problem may come from there testing infrastructure.

**Comment by NemOry** [comment] 2016-09-30 13:36
I also got my app rejected yesterday due to "NOT SUPPORTING IPV6". I only use AlamoFire and AWS IOS SDK for communicating to APIs.

**Comment by AnthonyMDev** [comment] 2016-09-30 21:35
As @cnoon has stated, this library has full IPV6 support. This is very likely not an issue with `Alamofire` and is rather due to IPV6 compatibility issues with your server, a third-party service you are using, or possibly, as @YacineVC suggested, an error in Apple's testing infrastructure.

**Comment by hellmund** [comment] 2016-10-09 09:54
@cnoon I can confirm from our recent Apple submission, that the reachability check fails in IPv6-only networks as @nikita-leonov described. In our case that was actually the reason for getting rejected by Apple, because we were relying on that functionality as preflight check. Once we remove the reachability check (that was the only change) and re-submitted, we passed review.

It's a bit tricky, as the failing cannot be reproduced in a mixed environment mit DNS64/NAT64 networks. But it will fail in the IPv6-only network which Apple is using (at least for spot tests) when submitting iOS apps for review.

I'd suggest to either remove the reachability check completely as implemented at the moment - and/or make it more clear to users of Alamofire that the reachability check must not be used for preflight check but only for diagnostic purposes on IPv4 or mixed networks AFTER identifying a connectivity issue, as suggested by Apple: https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW25
Otherwise there is a high chance that quite a few more developers are encountering this pitfall.

**Comment by adrimarti** [comment] 2016-10-11 07:51
How can I remove the reachability check?
I am getting my app rejected by Apple cause of this issue.

**Comment by niennonno** [comment] 2016-10-12 06:55
@hellmund can you help as to how to remove this check?

**Comment by kcharwood** [comment] 2016-10-12 12:48
@hellmund Yes you should definitely not be using reachability has a pre-flight check.

It may be best to open up a dev forum discussion and get Quinn involved. I chatted with him about this at WWDC, and there is just a lot of confusion here.

**Comment by hellmund** [comment] 2016-10-12 21:37
@niennonno @adrimarti We simply ended up removing the call to NetworkReachabilityManager and its "isReachable" check from our app's loading sequence. Now we are only checking ourselves if the loading sequence exceeds a certain threshold number of seconds. If so, we display a dialog to the users, giving them the option to restart the loading process.

**Comment by jshier** [comment] 2016-10-12 23:38
@hellmund You should also confirm that your backend is accessible through a pure IPv6 network, as we see that a lot, as many backends still require an IPv6to4 bridge for connectivity. Otherwise, recommended best practice is to allow requests to fail and then check reachability to determine your next steps.

**Comment by niennonno** [comment] 2016-10-13 08:33
@hellmund not able to find any call to the manager on my side. Can you please help out?
