### ISSUE TITLE
Concurrency Crashes Using Xcode 13.2/.1 and Bitcode Issue on Xcode 13.3

### ISSUE THREAD

**Issue by LuckyPia** [Alamofire/Alamofire#3529] opened 2021-12-20 06:18 UTC
Launch times for models below iOS13 ` libswift_ Concurrency.dylib (which was built for iOS 13.0) `, because '5.5.0' supports Concurrency, but only supports models above iOS 13. Please limit the usage environment of Concurrency

**Comment by jshier** [comment] 2021-12-20 06:35
It seems that iTunes Connect doesn't strip the concurrency binary out of app's deployed back to iOS 12. Stay on Alamofire 5.4.4 until that is fixed.

**Comment by qinqi777** [comment] 2021-12-22 02:44
I have run into the same issue, solved by pod 'Alamofire', '5.4.4'

**Comment by jshier** [comment] 2021-12-27 05:53
Pinning this until Apple ships a fix.

**Comment by x2web** [comment] 2022-01-19 11:57
Build with Xcode 13.1 to avoid crash on iOS 12  and earlier.

**Comment by jshier** [comment] 2022-01-24 17:04
To clarify: if you are deploying to a 2018 Apple OS or earlier (iOS 12, macOS 10.14, etc.) you have two options: remain on Alamofire 5.4.4 or Xcode 13.1. If you're targeting the 2019 OSes or newer, you shouldn't encounter this issue at all.

As for a fix, we're working to see if using CocoaPods subspecs and a separate SPM module may allow users to avoid the concurrency feature if they aren't using it. It's also possible Apple may fix this, we just can't know when.

**Comment by jshier** [comment] 2022-01-30 04:11
Looks like Xcode 13.3 beta 1 fixes multiple concurrency issues, including runtime issues on iOS 13 and 14, as well as this issue on older OSes. Hypothetically you could copy the concurrency compatibility library from Xcode 13.3 to your app built with Xcode 13.2.1 to also fix the issue.

Given that fact, I don't think we want to support a separate concurrency module or other workaround long term, so until Xcode 13.3 ships, everyone should keep using the existing workarounds. We may also want to consider moving the concurrency requirement to 5.6 when Xcode 13.3 ships so that users of the latest Alamofire version always avoid the broken version.

**Comment by mharlowfod** [comment] 2022-02-25 23:23
Confirmed 5.4.4 fixes issues on iOS 12 devices experienced with Xcode 13.2 and AF 5.5. Looking forward to an xcode fix soon if it really happens.

**Comment by jshier** [comment] 2022-03-03 18:11
This should be fixed in Xcode 13.3, which will likely be released next week after the Apple event.

**Comment by kambala-decapitator** [comment] 2022-03-14 09:36
> This should be fixed in Xcode 13.3, which will likely be released next week after the Apple event.

has anyone confirmed this already?

**Comment by jianpx** [comment] 2022-03-15 01:01
@jshier Xcode 13.3 has released! You can try.

**Comment by gabors** [comment] 2022-03-15 17:59
Xcode 13.3 has it's own set of problems it seems.
I cannot get any of my apps process for TestFlight. https://developer.apple.com/forums/thread/701949?page=1#707260022

**Comment by jianpx** [comment] 2022-03-18 00:35
@LuckyPia I have tried Xcode 13.3, it can fix this problem.

**Comment by gabors** [comment] 2022-03-18 00:39
@jianpx when I use Xcode 13.3 builds fail processing after upload to AppStore connect when using Alamofire 5.5.0 or 5.4.4.
Getting ITMS-90562: Invalid Bundle

**Comment by jshier** [comment] 2022-03-18 00:41
@gabors Alamofire 5.4.4 should work fine, as it doesn't include any concurrency code. Unfortunately Xcode 13.3 has it's own concurrency bug where any inclusion of concurrency code will break BitCode processing when deployed back to iOS 13 or 14. You can turn off BitCode, keep using Xcode 13.2.1 (and deal with its bugs), or keep using Alamofire 5.4.

I'll open a separate issue to track the BitCode problem but since it seems like Apple can't fix these issues I'll likely have to separate out the concurrency code into its own subspec (for CocoaPods) or module (for SPM). Carthage users are likely out of luck.

**Comment by gabors** [comment] 2022-03-18 00:52
> @gabors Alamofire 5.4.4 should work fine, as it doesn't include any concurrency code. Unfortunately Xcode 13.3 has it's own concurrency bug where any inclusion of concurrency code will break BitCode processing when deployed back to iOS 13 or 14. You can turn off BitCode, keep using Xcode 13.2.1 (and deal with its bugs), or keep using Alamofire 5.4.
> 
> I'll open a separate issue to track the BitCode problem but since it seems like Apple can't fix these issues I'll likely have to separate out the concurrency code into its own subspec (for CocoaPods) or module (for SPM). Carthage users are likely out of luck.

Thank you @jshier 
I don't have any other packages or code that use async/await.
I am not sure why, but when I pinned the Alamofire SPM to 5.4.4 and rebuilt my apps they still fail processing with the above error of  ITMS-90562: Invalid Bundle when using Xcode 13.3. When I inspected the ipa file the libswift_ Concurrency.dylib was still there.
Don't really want to disable bitcode processing, so I rolled back to Xcode 13.2.1 for now, but would love to understand why the libswift_ Concurrency.dylib was still there in the Frameworks folder of the ipa.

**Comment by gabors** [comment] 2022-03-20 07:35
@jshier I apologize for misleading you, it turns out that I did have another package (GRDB) in my project that had added async/await and I did not notice.

When I rolled back Alamofire 5.4.4 in a different app I was able to use Xcode 13.3 without any issues.

TBH Apple's async/await is becoming a pita ;)

**Comment by jshier** [comment] 2022-04-11 19:00
Looks like Xcode 13.3.1 is out and fixes the BitCode issue. Please give it a try! If it fixes the deployment issues we may just bump the requirement for the concurrency features to Swift 5.6.1 rather than 5.5.1 (Xcode 13.2) instead of shipping a separate concurrency module.

**Comment by gabors** [comment] 2022-04-12 20:40
> Looks like Xcode 13.3.1 is out and fixes the BitCode issue. Please give it a try! If it fixes the deployment issues we may just bump the requirement for the concurrency features to Swift 5.6.1 rather than 5.5.1 (Xcode 13.2) instead of shipping a separate concurrency module.

@jshier works for me now with Xcode 13.3.1 and latest Alamofire release

**Comment by jshier** [comment] 2022-04-12 20:42
@gabors Thanks for confirming! Bumping the required Swift compiler for the concurrency features is up as #3590, so this should get merged and released soon.

**Comment by jshier** [comment] 2022-04-17 19:42
I believe this is finally resolved with Alamofire 5.6.0. The concurrency features have been updated to require Swift 5.6.0 (Xcode 13.3), so anyone still using Xcode 13.2/.1 shouldn't see it built at all, which should fix the runtime issues. Additionally, make sure to use Xcode 13.3.1 to avoid the bitcode issue introduced in Xcode 13.3.0. 

Thanks everyone!

**Closed by jshier** 2022-04-17 19:42 UTC
