### ISSUE TITLE
New downloadProgress methods are ambiguous

### ISSUE THREAD

**Issue by thebluepotato** [Alamofire/Alamofire#1467] opened 2016-09-07 12:47 UTC
PR #1455 introduced a few very nice additions to handle progress of various requests.

```swift
Alamofire.download(url)
.downloadProgress { progress in
    // Called on main dispatch queue by default
    print("download progress: \(progress.fractionCompleted)")
}
.downloadProgress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
    // Called on main dispatch queue by default
    print("Read: \(bytesRead), Total Read: \(totalBytesRead), Total Expected: \(totalBytesExpectedToRead)")
}
.response { response in
    debugPrint(response)
}
```
There's no issue using `.downloadProgress { bytesRead, totalBytesRead, totalBytesExpectedToRead in`, with or without parenthesis, because the context is clear.
However for the `ProgressHandler` closure, the compiler complains that `.downloadProgress { progress in` is an "ambiguous use of 'downloadProgress(queue:closure:)'". It seems to be somehow mixing up the one-argument `ProgressHandler` with the three-argument `DownloadProgressHandler` for some reason.  The workaround is writing :
 
```swift
Alamofire.download(url)
.downloadProgress { (progress: Progress) in
    // Called on main dispatch queue by default
    print("download progress: \(progress.fractionCompleted)")
}
````
I think this is mostly a Swift interpreter bug because I can't fathom why it's mixing these up. Because the current implementation is _very_ elegant, I'd say it's only something to take into account when rewriting the README examples.

**Comment by cnoon** [comment] 2016-09-07 14:25
Interesting...thanks for reporting @thebluepotato!

Any chance you could put together a unit test or post sample code here that code reproduce the ambiguity warning? I haven't seen this error yet and I'd like to be able to avoid it without having the specify the `Progress` type in the single parameter closure case. I'd much rather get this fixed now since we're looking to release a bunch of things today.

**Comment by thebluepotato** [comment] 2016-09-07 16:04
The time I get home it'll be the start of Apple's presentation but I'll try my best to provide a sample just after it!

**Comment by thebluepotato** [comment] 2016-09-07 16:10
But I can already tell you that this bug is really "bugging" me because I've reproduced it a few times, fixing it with the workaround. However one time it compiled _with_ the workaround, I removed the workaround (i.e. had only `{progress in`) and it compiled fine (!!!) but only once then it complained about ambiguity again when compiling again. I'm guessing it "remembered" the explicit `Progress` annotation for a short while but at the next compilation it type-checked it again and couldn't infer type from context...

**Comment by thebluepotato** [comment] 2016-09-07 19:33
Sample code producing the bug : 

```swift
func downloadTest(progressHandler: @escaping (Double) -> Void, completion: @escaping (URL) -> ()) {
    let url = "https://s3.amazonaws.com/x265.org/video/BigBuckBunny_2000h264.mp4"
    let destination = Alamofire.DownloadRequest.suggestedDownloadDestination()
    
    Alamofire.download(url, to: destination)
        .downloadProgress { progress in
            progressHandler(progress.fractionCompleted)
            print(progress)
        }
        .response { downResponse in
            if let error = downResponse.error {
                print("ERROR: \(error)")
                print("REQUEST: \(downResponse.request)")
                print("RESPONSE: \(downResponse.response)")
            } else {
                completion(downResponse.destinationURL!)
            }
    }
}
```
![bug](https://cloud.githubusercontent.com/assets/2539639/18325671/99f48a92-7542-11e6-8562-6a70d65fa5d7.jpeg)

**Comment by thebluepotato** [comment] 2016-09-07 21:11
Now I'll wait for the GM to download test it again. I see the gm-feature branch adds `@escaping`to the `closure:` parameter and maybe it'll help? I'll check back with.

PS: I've seen you work at Nike! Kudos on the new Watch 👍

**Comment by thebluepotato** [comment] 2016-09-07 22:06
So here are the results : I've added the `@escaping` tags to Alamofire in the GM and it doesn't help my bug. It still finds `.downloadProgress{ progress in` ambiguous...

**Comment by cnoon** [comment] 2016-09-08 02:28
Cool, thanks for reporting @thebluepotato...we'll certainly dig into it.

**Comment by cnoon** [comment] 2016-09-10 08:49
Thank you for opening this issue and providing the failing test @thebluepotato! Much appreciated!

After much investigation, there was nothing we could do that would allow us to keep both variant APIs without having to specify the type on the `progress` closure parameter. Because of this, I decided to remove the `Int64` variants for both upload and download progress. These changes have been pushed in `master` in commit 7925a0a7.

Thanks again for all your help here! 🍻

**Closed by cnoon** 2016-09-10 08:49 UTC
Labels: bug, needs investigation, request

**Comment by thebluepotato** [comment] 2016-09-10 15:01
I'm glad to help! 🍻

**Comment by iOSvarinder** [comment] 2018-06-27 12:40
can anyone tell me how to call this function.. thanks
