### ISSUE TITLE
Crash when request JSON SWIFT 3.0

### ISSUE THREAD

**Issue by AleyRobotics** [Alamofire/Alamofire#1686] opened 2016-10-11 13:03 UTC
xCode 8.1 beta, iOS 10.1 beta, swift 3.0, real device iPhone 5 (at simulator works great!)
crash when calling Alamofire.request(request).responseJSON{....}

 Request.swift

```

// MARK: State

    /// Resumes the request.
    open func resume() {
        guard let task = task else { delegate.queue.isSuspended = false ; return }

        if startTime == nil { startTime = CFAbsoluteTimeGetCurrent() }

        task.resume()

        NotificationCenter.default.post(
            name: Notification.Name.Task.DidResume,
            object: self,
            userInfo: [Notification.Key.Task: task] <<<<=== EXC_BAD_ACESS
        )
    }
```

back trace
  STAR thread #1: tid = 0x73404, 0x00a92bbe libswiftCore.dylib`swift::metadataimpl::ValueWitnesses<swift::metadataimpl::OpaqueExistentialBox<0u> >::initializeWithCopy(swift::OpaqueValue*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*) + 12, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2)
    frame #0: 0x00a92bbe libswiftCore.dylib`swift::metadataimpl::ValueWitnessesswift::metadataimpl::OpaqueExistentialBox<0u >::initializeWithCopy(swift::OpaqueValue_, swift::OpaqueValue_, swift::TargetMetadataswift::InProcess const_) + 12
    frame #1: 0x00a8f9ba libswiftCore.dylib`swift::OpaqueValue_ tuple_initializeWithCopy<false, false>(swift::OpaqueValue_, swift::OpaqueValue_, swift::TargetMetadataswift::InProcess const*) + 38
    frame #2: 0x008a6750 libswiftCore.dylib`Swift._ArrayBuffer.getElement (Swift.Int, wasNativeTypeChecked : Swift.Bool) -> A + 112
    frame #3: 0x008b7c30 libswiftCore.dylib`Swift.Array.subscript.getter : (Swift.Int) -> A + 152
    frame #4: 0x008b8d64 libswiftCore.dylib`protocol witness for Swift.Collection.subscript.getter : (A.Index) -> A.Iterator.Element in conformance <A> Swift.Array<A> : Swift.Collection in Swift + 24
    frame #5: 0x00a70548 libswiftCore.dylib`protocol witness for Swift.IndexableBase.subscript.getter : (A.Index) -> A._Element in conformance <A> Swift.Array<A> : Swift.IndexableBase in Swift + 24
    frame #6: 0x0088fe18 libswiftCore.dylib`Swift.IndexingIterator.next () -> Swift.Optional<A._Element> + 528
    frame #7: 0x009091c4 libswiftCore.dylib`static Swift._NativeDictionaryStorage.fromArray (Swift.Array<(A, B)>) -> Swift._NativeDictionaryStorage<A, B> + 436
    frame #8: 0x00908f7c libswiftCore.dylib`Swift.Dictionary.init (dictionaryLiteral : Swift.Array<(A, B)>...) -> Swift.Dictionary<A, B> + 80
  STAR frame #9: 0x00443450 Alamofire`Request.resume(self=<unavailable>) -> () + 736 at Request.swift:205
    frame #10: 0x00494e3c Alamofire`SessionManager.request(urlRequest=<unavailable>, self=<unavailable>) -> DataRequest + 716 at SessionManager.swift:260
    frame #11: 0x004948b4 Alamofire`SessionManager.request(url=<unavailable>, method=<unavailable>, parameters=<unavailable>, encoding=<unavailable>, headers=<unavailable>, self=<unavailable>) -> DataRequest + 776 at SessionManager.swift:237
    frame #12: 0x00423514 Alamofire`request(url=<unavailable>, method=<unavailable>, parameters=<unavailable>, encoding=<unavailable>, headers=<unavailable>) -> DataRequest + 536 at Alamofire.swift:146
    frame #13: 0x0013f4ec MyApp`ContentManager.(self=0x17653c70) -> ()).(closure #1) + 240 at ContentManager.swift:86
    frame #14: 0x000d53d8 MyApp`thunk + 56 at SELiveVC.swift:0
    frame #15: 0x010e1d66 libdispatch.dylib`_dispatch_call_block_and_release + 10
    frame #16: 0x010e1d52 libdispatch.dylib`_dispatch_client_callout + 22
    frame #17: 0x010e65f0 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 1006
    frame #18: 0x1e006a16 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
    frame #19: 0x1e004cfe CoreFoundation`__CFRunLoopRun + 1422
    frame #20: 0x1df54072 CoreFoundation`CFRunLoopRunSpecific + 486
    frame #21: 0x1df53e80 CoreFoundation`CFRunLoopRunInMode + 104
    frame #22: 0x1f700bfc GraphicsServices`GSEventRunModal + 156
    frame #23: 0x2310e82e UIKit`-[UIApplication _run] + 574
    frame #24: 0x23108f60 UIKit`UIApplicationMain + 150
    frame #25: 0x0008abd8 MyApp`main + 172 at AppDelegate.swift:13
    frame #26: 0x1d71e50a libdyld.dylib`start + 2

**Comment by jshier** [comment] 2016-10-18 17:43
Sorry, we won't be able to look into this until we have devices with iOS 10.1. In the mean time, can you retest on the latest beta. This looks like it could be an underlying Swift issue.

**Comment by pixelfreak** [comment] 2016-10-19 00:47
Seeing this too on iOS 10.0.2

**Comment by pixelfreak** [comment] 2016-10-19 00:48
It doesn't happen consistently. Using the same params, it seems to only crash 50% of the time.

**Comment by adrimarti** [comment] 2016-10-21 10:58
I am getting my app rejected due to this issue :C

**Comment by sanjuraj85** [comment] 2016-10-21 13:29
On https:// challenge demand user client certificate. How can i pick certificate from profile (General/DeviceManagement/DigitalWorkSpace/Profile  and pass it to for?

The same certificate prompted on Safari Browser while accessing.

**Comment by pixelfreak** [comment] 2016-10-21 22:24
Any way we can help with this? iOS 10 has been out for quite some time. It'll be awesome if we can get this resolved soon. Our development is on a stand-still.

**Comment by jshier** [comment] 2016-10-22 22:50
@AleyRobotics @pixelfreak @adrimarti I'm sorry, but I can't reproduce this issue at all. Our tests pass on a variety of simulator types with each optimization level. We're going to need to see the calling code that leads to this crash to be able to reproduce it. @pixelfreak You mentioned "using the same parameters", can we get a code sample with those parameters that causes this issue for you?

**Comment by pixelfreak** [comment] 2016-10-22 23:08
@jshier This does not happen in simulator. Only happens on a device. 

There is nothing special with the call itself. It's just a vanilla request:

```
Alamofire.request("someHttpsURL", method: .post, parameters: params, encoding: JSONEncoding.default, headers: headers).responseJSON
{
    response in
}
```

**Comment by jshier** [comment] 2016-10-22 23:16
@pixelfreak I'm sorry, but like I said, I tried to replicate on both device (iPhone 7, iPhone 4S) and the simulator. Can you put together a sample project that reproduces the issue, even if it's on device?

**Comment by cleverliz** [comment] 2016-10-31 04:16
@AleyRobotics @jshier  I hava encountered a similar problem ,do you know how to fix it?

**Comment by EonKid** [comment] 2016-11-10 05:41
I have similar issue and due to this my app is rejected by Apple.The crash occurred on iPad devices while the app is working fine on iPhone devices. I am attaching the Apple crash log file.It seems that the error occurred in Request handler of Alamofire
![screen shot 2016-11-10 at 11 06 41 am](https://cloud.githubusercontent.com/assets/13067085/20165782/50838770-a736-11e6-9a17-ae3dd7ae9e32.png)
Please try to fix this as soon as possible

**Comment by cnoon** [comment] 2016-11-12 23:31
Hey everyone,

I'm going to close this issue out because there's nothing for us to really go on here. We have been unable to reproduce this issue through numerous attempts and no one has posted a sample project that can reproduce the issue.

In the future, please provide more information so we're able to help you debug the issue. We want to help, but there's nothing here for us to actually help with.

Best of luck. 🍻

**Closed by cnoon** 2016-11-12 23:31 UTC
Labels: needs feedback, needs investigation

**Comment by pauarmada** [comment] 2016-12-12 14:16
Anyone tried on iOS 9.1?
