### ISSUE TITLE
EXC_BAD_ACCESS at Session

### ISSUE THREAD

**Issue by dimpiax** [Alamofire/Alamofire#3122] opened 2020-03-19 14:02 UTC
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
Create `MoyaProvider` init with initializing default `Session`.

The project tested from clean state, previously removing **Derived Data**.

## What did you expect to happen?
The same flow as was in previous version, **v4.9.1**.

## What happened instead?
Getting the error: `Thread 1: EXC_BAD_ACCESS (code=1, address=0xfffffffffffffff8)`,
at the **Session.swift:313** line, regarding access to the `convertible`, in `DataRequest` creation.

## Alamofire Environment

**Alamofire version:** 5.0.4
**Xcode version:** Version 11.3 (11C29)
**Swift version:** 5.1.3
**Platform(s) running Alamofire:** iOS 10.3
**macOS version running Xcode:** 10.15.3 (19D76)

**Comment by jshier** [comment] 2020-03-22 21:06
In order to properly investigate a crash like this, we need a few things. These include:

- The crashing call stack from your crash report.
- Code snippets of your usage relevant to the crash report.
- Ideally, a sample project which replicates the issue.

Without those we're investigating in the dark. My brief research has shown that crashes at `address=0xfffffffffffffff8` are usually due, at least in part, to compiler bugs or other issues in the language.

**Comment by dimpiax** [comment] 2020-03-22 21:09
Very strange, I got this error when I use `Alamofire` as dependency for an SDK, and cocoapods installs it via `.podspec`. 
Literally, If I call just `Alamofire.Session()` the application crashes.

**Comment by jshier** [comment] 2020-03-22 21:11
To me that definitely points to some sort of compilation issue. If you build the same thing using SPM, do you see the same issue?

**Comment by jshier** [comment] 2020-03-22 21:14
Another possibility would be #3051 if you're using a free developer account.

**Comment by dimpiax** [comment] 2020-03-22 21:15
If I install dependency and use it directly in the application, there is no any real time crash error with it.
Only in the case, when I use this through SDK. As I've noticed the bug wasn't not exist with version 4.9.1.

> Another possibility would be #3051 if you're using a free developer account.
Not my case.

**Comment by michaeleisel** [comment] 2020-03-24 21:07
I have this same issue, exc_bad_access in Session. It occurred after I moved AlamofireImage and Alamofire off Carthage and into their own separate frameworks, built with release configuration for distribution and as static libraries.

**Comment by dimpiax** [comment] 2020-03-24 21:09
Hi @michaeleisel, did you try with **v5.0.5**?

**Comment by michaeleisel** [comment] 2020-03-24 21:10
Was there a fix for this issue?

**Comment by dimpiax** [comment] 2020-03-24 21:55
It can be, but in my case, I've updated other details also, like `RxSwift` for `Moya` etc.

**Comment by michaeleisel** [comment] 2020-03-24 23:32
You're saying that, at one point, it fixed the issue, but then you made other changes that caused the error to surface again? What specifically changed up to 5.0.5 that helped this issue?

**Comment by jshier** [comment] 2020-03-25 00:08
There are no changes in 5.0.5 that would affect this. It's most likely some sort of build or linking issue that affects your projects specifically. You aren't trying to build with library stability or anything are you? And if anyone can make a small project that reproduces this issue that'd be great.

**Comment by michaeleisel** [comment] 2020-03-25 00:26
I am indeed building with library stability, so that this static library can be used across dev machines

**Comment by jshier** [comment] 2020-03-25 01:13
Alamofire doesn't support library stability and likely never will due to the restrictions it places on library changes. It's generally unsafe to turn on library stability for libraries that don't support it, and it isn't generally recommended unless you're shipping your own binary products. If you are shipping binary products, all of your dependencies must also support library stability mode or you can run into issues like this. If you want to share static binaries locally, you don't need library stability, you just need to ensure your machines are using the same version of the Swift compiler.

**Comment by michaeleisel** [comment] 2020-03-25 01:45
I see. If there was some way to fail fast and alert the dev about this, that'd be great. My impression was that there weren't really caveats like this, and I imagine a lot of other devs might be surprised by this as well. Also, +1 to reconsidering that stance on module stability. You can see that module stability is important to lots of devs, and that the workaround is a major tradeoff, from the comments starting at https://github.com/Carthage/Carthage/pull/2902#issuecomment-574692640

**Comment by jshier** [comment] 2020-03-25 02:07
There is no tooling to detect breaking changes, which is one of the reasons Alamofire won't be supporting the mode. There are a host of drawbacks to enabling library evolution mode, as outlined in [this blog post](https://swift.org/blog/library-evolution/). Like I said, unless you're shipping a binary library to the public, you don't need to enable library evolution, and Apple doesn't recommend it. ABI stability is enough for CI and other local build system to produce static artifacts that are compatible across machines, as long as the compiler version is the same.

**Comment by dimpiax** [comment] 2020-03-25 09:19
> You're saying that, at one point, it fixed the issue, but then you made other changes that caused the error to surface again? What specifically changed up to 5.0.5 that helped this issue?

> but then you made other changes that caused the error 
Where had I said that?

**Comment by dimpiax** [comment] 2020-03-25 09:20
@michaeleisel 

> You're saying that, at one point, it fixed the issue, **but then you made other changes that caused the error to surface again**? What specifically changed up to 5.0.5 that helped this issue?

Where had I said that?

**Comment by michaeleisel** [comment] 2020-03-25 15:50
@dimpiax disregard

**Comment by michaeleisel** [comment] 2020-03-25 15:53
@jshier it makes a lot of things about tooling more difficult. For example, build systems can't cache the Alamofire library as a build artifact, unless they cache it for each compiler version. Or you could limit people to just one compiler version, e.g. Swift 5.1 which seems to be in Xcode 11.0-11.3. But then people start using Xcode 11.4, or some future beta to make sure that their app works on it, and you have problems.

**Comment by jshier** [comment] 2020-03-25 17:06
Yes, it would be up to the individual projects to manage their build artifacts and process, including Xcode versions. That's a choice made by those projects. At least in that case there will be a nice build time error saying that the static products were built by a different version of the Swift compiler, making it much easier to see and fix the issue than the library evolution crashes reported here.

**Comment by jshier** [comment] 2020-04-05 01:03
I think we've discovered the cause of the issue, so I'm closing this issue.

**Closed by jshier** 2020-04-05 01:03 UTC
Labels: library evolution, needs investigation

**Comment by dimpiax** [comment] 2020-04-05 11:56
@jshier could you provide the cause?

**Comment by jshier** [comment] 2020-04-05 21:02
@dimpiax It seems likely that your SDK was compiled with library evolution mode enabled, which Alamofire doesn't support and can cause crashes if a non-resilient change is made to the library.
