### ISSUE TITLE
Creating a Manager with Default Configuration doesn't use configuration in today extension

### ISSUE THREAD

**Issue by florianwalter** [Alamofire/Alamofire#332] opened 2015-02-03 23:26 UTC
I'm using this code in an app and in its today extension:
```
var defaultHeaders = Alamofire.Manager.sharedInstance.session.configuration.HTTPAdditionalHeaders ?? [:]
defaultHeaders["User-Agent"] = "MyUserAgentString"
let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
configuration.HTTPAdditionalHeaders = defaultHeaders
let manager = Alamofire.Manager(configuration: configuration)
```
This works perfectly in the app, but in the extension it seems like the configuration is not used, because the user-agent-string is the default Alamofire string.

**Comment by cnoon** [comment] 2015-05-07 04:48
Hi @florianwalter, our apologies for not getting back to you sooner. With that said, I've created a sample project called [AlamofireToday](https://github.com/cnoon/Alamofire-Example-Apps/tree/master/AlamofireToday) with your exact logic and it works as intended. I would encourage you to check it out. 

Hopefully you can spot the difference between what I've created and what you are doing. I'm going to close this issue out since I cannot reproduce it. If you are able to modify my project and produce your reported behavior, then please submit a PR against my example app and reopen this issue.

Cheers 🍻

**Closed by cnoon** 2015-05-07 04:48 UTC
Labels: bug, needs investigation, url session

**Comment by kcharwood** [comment] 2015-05-13 13:41
@cnoon I'd probably remove the 1.2.2 tag here since there was no code changes.

**Comment by cnoon** [comment] 2015-05-13 14:47
Thanks @kcharwood, good catch. Will remove.
