### ISSUE TITLE
Deadlock inside the session's delegate NSOperationQueue

### ISSUE THREAD

**Issue by groovz** [Alamofire/Alamofire#1075] opened 2016-02-22 17:06 UTC
Hi

I'm experiencing a deadlock inside one of the operations in the NSUrlSession delegate queue. it happens when i'm doing at least one download and one upload simultaneously (all requests are done through the default Alamofire manager). Is there any problem doing so from multiple threads? (either in NSUrlSession or Alamofire)
it seems to be stuck on __psynch_mutexwait in one of the operations in the nsurlsession delegate queue.  

![untitled](https://cloud.githubusercontent.com/assets/16528276/13226579/c8c9503a-d99a-11e5-987e-8121030285a7.png)

**Comment by cnoon** [comment] 2016-02-23 02:57
I'm not really sure what to tell you here @groovz. At this point, I can't see any actual Alamofire calls being made. Therefore, it's difficult for me to say exactly what's going on. It appears as though you've managed to deadlock the session delegate queue for a URL session (`com.apple.NSURLSession-work`), but that's just a theory at this point. Without a solid code sample or a sample project, there's very little to go on.

I'm going to close this out for now since I can't see any further action I can take. If you provide more info, I'd be happy to re-open and investigate further.

Cheers. 🍻

**Closed by cnoon** 2016-02-23 02:57 UTC

**Comment by groovz** [comment] 2016-02-23 08:33
I did manage to do that, I verified that by creating an concurrent NSOperationQueue and setting it as the delegate queue when creating the session object in Alamofire and it deadlocked, but still was able to process new requests. If I leave it with default serial queue it deadlocks and the whole queue is waiting for it finish forever (therefore no new requests are processed)

here's an example code for upload and download I'm doing (they are both called on 2 different queues, one of them is usually called on the main thread)

`        Alamofire.upload(.POST, uploadURL,
        multipartFormData: { multipartFormData in
                multipartFormData.appendBodyPart(data: x.dataUsingEncoding(NSUTF8StringEncoding)!, name: "X")
                multipartFormData.appendBodyPart(data: fileData, name: "file", fileName: "Y", mimeType: "application/octet-stream")
            }
        },
        encodingCompletion: { encodingResult in
            switch encodingResult {
            case .Success(let upload, _, _):
                upload.response { (request, response, data, error) -> Void in
                    if let error = error {
                        callback("Failure", "\(error)")
                    } else {
                        callback("SUCCESS", nil)
                    }
                }
            case .Failure(let encodingError):
                callback(nil, "Failed due to \(encodingError)")
            }
        }
    )`  

`    Alamofire.download(.GET, downloadUrl, parameters: ["a": "a", "b": "b"], destination:
        {
            tempURL, response in
            return path
    }).response {
        (request, response, _, error) in
        let data = NSData(contentsOfURL: path)
        doSomeStuffWithDownloadedData(data)
        // make another request after download completed
        Alamofire.request(.GET, requestUrl, parameters: ["c":"c", "d":"d"]).response {
            request, response, data, error in
            if let e = error {
                log.error("request failed, \(e)")
            }
        }
    }`

**Comment by cnoon** [comment] 2016-02-27 18:19
Hmmmm...thanks for all the info, but I still can't pinpoint any actual issue here with Alamofire. We haven't had a single report of deadlocking with parallel uploads and downloads. With the way the logic is constructed, I'm very doubtful the issue itself lies in Alamofire.

In all my networking experience, I've generally found it to be a bad idea to use a concurrent URL session delegate queue, mainly because it can lead to deadlocks. The problem is that the queue doesn't call the delegate for a single request on the same thread, it will jump threads. So two delegate callbacks you would expect to receive serially will actually happen in parallel. This can lead to really odd runtime logic and can easily lead to deadlock scenarios.

> Generally, avoid concurrent session delegate queues if possible unless you really have an extremely good reason to do so. It's much easier to keep a serial session delegate queue and then dispatch immediately when you receive the delegate call. Then you have full control.

As for what's actually causing your deadlock, I cannot be certain. As I mentioned before, I really doubt it's an issue with Alamofire because we haven't had a single report of this until now. Additionally, with what you've mentioned about changing out the session delegate queue and also making pubnub requests at the same time, I'm fairly certain this is a deadlock scenario you've created on your own end. Unfortunately, there's not much I can do to help you debug any further. The only other thing I can think of to help you is to turn off all the pubnub logic and use a serial session delegate queue and try to resolve your deadlock. You most likely won't be able to trace the root cause of it until you start eliminating some of the possible options.

Best of luck! 🍻

**Comment by groovz** [comment] 2016-02-28 08:44
OK,

I'm not sure you understood me correctly, because I changed the delegate queue to be concurrent just to check if that's where the deadlock happens, and it confirmed that. The deadlock was on the serial queue beforehand.

Anyway, I dug a bit deeper into this problem and I think as well it is something in my code that causes that by I'm not yet sure what, because the deadlock is inside apple's code.
the deadlock itself happens inside the delegate queue when doing two request in alamofire one after another (on of them is upload, the second could by anything), but the calls to alamofire have to be in a specific order because it does not reproduce always.
the deadlock happens inside [NSBlockOperation main] in the objc_sync_enter call that waits forever.
My calls to alamofire are on the main thread and in some of their completion blocks I do another request to alamofire (is that fine to do that?).

**Comment by groovz** [comment] 2016-02-28 09:39
Another thing that I found from printing every time objc_sync_enter/exit inside [NSBlockOperation main] is called. Is that the extra lock does not happens in [NSBlockOperation main] but in someplace else in the code, I don't know where yet.

**Comment by groovz** [comment] 2016-03-01 08:51
Solved it, wasn't related to alamofire or nsurlsession at all. 
Caused by a call to objc_sync_enter in my code (in a totally different class from the one with the alamofire calls) on an array (Apparently, this can cause very strange deadlocks to happen)

**Comment by cnoon** [comment] 2016-03-01 15:05
Cool...glad you figured it all out! 👍🏼
