### ISSUE TITLE
Alamofire crashes only when running archived app

### ISSUE THREAD

**Issue by eraducan** [Alamofire/Alamofire#2016] opened 2017-03-15 13:04 UTC
The same as: https://github.com/Alamofire/Alamofire/issues/1718
But it is crashing only in Objective-C project. 
Alamofire 4.4.0, installed via CocoaPods. 
The crash is throwing in 
<img width="622" alt="screen shot 2017-03-15 at 12 29 10 pm" src="https://cloud.githubusercontent.com/assets/18656835/23949620/986f90b2-0990-11e7-8c16-d9e2d064a862.png">

**Comment by jshier** [comment] 2017-03-20 01:08
There isn't much for us to do here. Make sure your optimization and SDK levels match and you're using the latest Xcode and Alamofire versions. If you can create a test project that reliably replicates the issue we may be able to investigate further. Otherwise this looks like a low level issue from Apple's side. I'm closing this report for now, but please comment with a test project if you get this to reliably reproduce.

**Closed by jshier** 2017-03-20 01:08 UTC
