### ISSUE TITLE
Multipart upload: file content not in the payload

### ISSUE THREAD

**Issue by top2tech** [Alamofire/Alamofire#555] opened 2015-06-29 16:17 UTC
In branch feature/multipart_form_data, try to upload some string and a file. The string is in the payload, but the file is not. 

### File url: 
assets-library://asset/asset.JPG?id=E2741A73-D185-44B6-A2E6-2D55F69CD088&ext=JPG

### Captured Traffic:

Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 340
Accept-Language: en-us
Accept: /
Connection: keep-alive
Connection: keep-alive
User-Agent: app01/1 CFNetwork/711.3.18 Darwin/14.3.0

--alamofire.boundary.2373462a015381c7
Content-Disposition: form-data; name="postdata"

{"Content":"Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation"}
--alamofire.boundary.2373462a015381c7--

### Code:

class func addPost(post:Post, fileUrls: [NSURL], callback:(Post) -> Void)
{
    let url = resRootUrl

    let jStr = Mapper().toJSONString(post, prettyPrint: false)
    let data = jStr?.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)

    println(fileUrls[0])

    sManager.upload(.POST, url,
        multipartFormData:
        {
            multipartFormData in
            multipartFormData.appendBodyPart(data:data!, name:"postdata")
            multipartFormData.appendBodyPart(fileURL: fileUrls[0], name: "unicorn")

        },
        encodingCompletion:
           {
              encodingResult in
                switch encodingResult {
                  case .Success(let upload, _, _):
                     upload.responseJSON
                    {
                       request, response, JSON, error in
                       println(JSON)
                    }
                  case .Failure(let encodingError):
                       println(encodingError)
            }
        }
    )

}

**Comment by cnoon** [comment] 2015-07-07 02:21
I would guess that when you are attempting to append the `fileURL` that it is actually failing. What happens if you do the following?

```swift
    multipartFormData:
    {
        multipartFormData in
        multipartFormData.appendBodyPart(data:data!, name:"postdata")
        let error = multipartFormData.appendBodyPart(fileURL: fileUrls[0], name: "unicorn")
        println(error)
    },
```

**Comment by top2tech** [comment] 2015-07-08 05:39
thanks, I can see the error, it says it's not file url.  The url is returned from UIImagePicker from photos with the following path:
    assets-library://asset/asset.JPG?id=E2741A73-D185-44B6-A2E6-2D55F69CD088&ext=JPG

Looks like this kind of asset library Url is not supported in multipartFormData.appendBodyPart ?
I changed to use NSData for the image, then it works fine.

**Comment by cnoon** [comment] 2015-07-08 15:16
Ah that makes sense. See this [thread](http://stackoverflow.com/a/13523463) for more information. I'm going to close this issue out since this is the expected behavior.

**Closed by cnoon** 2015-07-08 15:16 UTC
Labels: multipart form data, needs feedback

**Comment by rajeshsonu** [comment] 2017-04-07 08:55
what if i have path for video 
assets-library://asset/asset.mp4?id=1CEBF789-632D-4634-839E-5707D18CEBE9&ext=mp4 
how to upload it to server
