### ISSUE TITLE
Apple's update to their API policy - Required Reason

### ISSUE THREAD

**Issue by ColeBoel** [Alamofire/Alamofire#3761] opened 2023-08-18 18:56 UTC
[*] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

Apple is requiring all api calls that fall under this ruleset https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394
be added to a privacy manifest file.

## Feature Request

Some APIs that your app uses to deliver its core functionality — in code you write or included in a third-party SDK — have the potential of being misused to access device signals to try to identify the device or user, also known as fingerprinting. Regardless of whether a user gives your app permission to track, fingerprinting is not allowed. Describe the reasons your app or third-party SDK on iOS, iPadOS, tvOS, visionOS, or watchOS uses these APIs, and check that your app or third-party SDK only uses the APIs for the expected reasons.

## Value to Alamofire

This will be required regardless, just making sure the great team at alamofire is aware.

**Comment by jshier** [comment] 2023-08-18 19:00
Thanks for opening this! The only API we should need to care about is `systemUptime`, which we use as an absolute clock for `AuthenticationInterceptor`, which is the one valid use. It doesn't look like they've finalized support in SPM yet, so we'll have to see what final support looks like.

**Comment by ColeBoel** [comment] 2023-08-18 19:01
> Thanks for opening this! The only API we should need to care about is `systemUptime`, which we use as an absolute clock for `AuthenticationInterceptor`, which is the one valid use. It doesn't look like they've finalized support in SPM yet, so we'll have to see what final support looks like.

Yessir you are completely right! Thanks so much Jon!

**Comment by yupengyang** [comment] 2023-12-11 07:57
Apple published a [privacy update of app submission](https://developer.apple.com/news/?id=r1henawx). 

And Alamofire is on the [list](https://developer.apple.com/support/third-party-SDK-requirements/)

**Comment by jshier** [comment] 2023-12-11 14:54
@yupengyang Yes, I know. You can track the privacy manifest PR in #3792.

**Comment by gen-miyasaka** [comment] 2023-12-20 07:36
Are there any plans to support Signatures for SDKs?
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by jshier** [comment] 2023-12-20 20:18
Alamofire will support signatures as soon as Apple offers directions on how to support signatures for SPM, CocoaPods, and Carthage. I haven't been able to find any real details on what we're supposed to do, nor has Apple responded to any of my inquiries. Once we have a more concrete timeline I'll escalate.

**Comment by gen-miyasaka** [comment] 2023-12-21 07:22
Thank you for your response. I understand.

**Comment by lakshmankreditbee** [comment] 2024-01-16 07:52
Hi, when can we expect an update regarding this issue?

**Comment by kalsariyarahul** [comment] 2024-01-23 04:57
Hi, when can we expect an update regarding this issue?

**Comment by JLLA113** [comment] 2024-02-08 23:29
Hi, 

**Any news?**

Regards,

**Comment by mejim707** [comment] 2024-02-09 21:58
Hi, is there any update on the Privacy Manifest support for Almofire? Apple will soon disallow any app submissions that use Almofire if the SDK does not include this manifest. We would prefer to continue using the Almofire SDKs if possible.

**Comment by jshier** [comment] 2024-02-09 22:52
No need to ping anything, this will go out with the next update. I'm still waiting for some final confirmations from Apple (and am on vacation this week), and I need to integrate with CocoaPods and Carthage, but it'll go out before whatever date Apple announces.

**Comment by lxsvlog** [comment] 2024-02-19 02:31
> No need to ping anything, this will go out with the next update. I'm still waiting for some final confirmations from Apple (and am on vacation this week), and I need to integrate with CocoaPods and Carthage, but it'll go out before whatever date Apple announces.

According to Apple documentation requirements: "Signatures are also required in these cases where the listed SDKs are used as binary dependencies",
It seems that only libraries that are binary dependencies need to be signed. However, using cocoapods is a source code method, so signatures should not be required.

**Comment by jshier** [comment] 2024-02-19 02:32
Right, no signatures, but I still need to add the privacy manifest to the podspec and ensure the CocoaPods integration properly surfaces it in Xcode.

**Comment by mejim707** [comment] 2024-02-26 16:56
Curious, does this SDK share user data? And if not, why does it require the Privacy Manifest update? 

We will update to the latest regardless just to be safe, but with the deadline fast approaching, and issues we've already experiencing with other SDKs and the privacy reports, I'm wondering if this update is required.

**Comment by jshier** [comment] 2024-02-26 17:00
Given Alamofire's usage of newly restricted API (just `systemUptime` as a monotonic time source), a privacy manifest is required. If you need it now and you use SPM or Carthage, you should be able to use the `master` branch. CocoaPods support still needs to be added, and I need to test the final integration, but there will be a release before the deadline (which hasn't been announced).

**Comment by FONickReichard** [comment] 2024-02-26 17:51
Apple has announced two separate requirements for app submissions to App Store Connect. 

1. On December 7, 2023, Apple re-posted that the Privacy Manifest requirement is effective from spring 2024 (https://developer.apple.com/news/?id=r1henawx). 
2. Apple recently announced on February 6, 2024, starting **April 29**, apps must be built with Xcode 15 (https://developer.apple.com/news/?id=fxu2qp7b). 

While these requirements appear to be distinct, there seems to be a possibility that the Xcode 15 requirement, set for April 29, could also encompass the Privacy Manifest requirement?

**Comment by mejim707** [comment] 2024-02-26 18:03
@FONickReichard Yes you're correct, I also confirmed this directly with my apple rep. They will require SDKs to include the privacy manifests. The only unclear part is what SDKs actually require an update. As in, based on the above comment, if SDKs make use of private APIs, or as we know if SDKs share tracking details. 

But do ALL SDKs require the manifest of they don't track user data or include private APIs? This I don't know, and I've asked Apple for clarity there.

Thanks

**Comment by cesarbess** [comment] 2024-02-27 15:39
Hey all, i see this PR was merged: https://github.com/Alamofire/Alamofire/pull/3792 is there an estimate for when we can have a new official release with this included?

**Comment by joseph-newton-ck** [comment] 2024-02-28 18:52
> Hey all, i see this PR was merged: #3792 is there an estimate for when we can have a new official release with this included?

+1

**Comment by JernardDucon** [comment] 2024-03-01 18:03
> ...
> While these requirements appear to be distinct, there seems to be a possibility that the Xcode 15 requirement, set for April 29, could also encompass the Privacy Manifest requirement?
> 
> *Edit 2/26/24: I Interpreted April 29th as the "Spring of 2024" updated deadline. I wish Apple gave more details around the recent announcement.

Hi all,
Yesterday (Feb 29) Apple announced the [exact timelines](https://developer.apple.com/news/?id=3d8a9yyh) for this @FONickReichard. Warning emails are starting on March 13, and app rejections will start on May 1.

Could someone of the project maintainers confirm if the mentioned PR https://github.com/Alamofire/Alamofire/pull/3792 will be released before timelines?

**Comment by jshier** [comment] 2024-03-01 18:09
Of course they will.

**Comment by jshier** [comment] 2024-03-04 02:43
This has been release in 5.9.0.

**Closed by jshier** 2024-03-04 02:43 UTC
Labels: needs investigation

**Comment by PPasiekaN7** [comment] 2024-04-16 08:32
Are you planning to add Privacy file to version 4?
