### ISSUE TITLE
Xcode 12 Beta Archive issue

### ISSUE THREAD

**Issue by kamzab95** [Alamofire/Alamofire#3240] opened 2020-06-24 07:46 UTC
Since Xcode 12 is available in beta I've had to give it a try. There is some issue when trying to archive Alamofire.

`Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in HTTPHeaders.o
ld: symbol(s) not found for architecture armv7`

When it comes to this issue I am aware that it may be fault of new Xcode, I just would like to start the discussion on this topic.
## What did you do?

I've tried to archive Alamofire using new Xcode12-beta

## What did you expect to happen?

Successful archive.

## What happened instead?

Archive failed with error
`Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in HTTPHeaders.o
ld: symbol(s) not found for architecture armv7`
 
## Alamofire Environment

**Alamofire version:** 5.2.1
**Xcode version:** 12-beta
**Swift version:** 5.3 (swiftlang-1200.0.16.9 clang-1200.0.22.5)
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.15.4

**Comment by yuyedaidao** [comment] 2020-06-24 08:15
I have the same issue

**Comment by marcelofabri** [comment] 2020-06-24 09:06
Bumping the deployment target fixed it for me (I raised it to 12, which is my app's deployment target, but maybe a lower value would be enough).

**Comment by jshier** [comment] 2020-06-24 14:39
Which platforms were you archiving for?

**Comment by kamzab95** [comment] 2020-06-24 14:42
just for iOS

**Comment by jshier** [comment] 2020-06-24 14:48
@marcelofabri A deployment target of iOS 11 should work, since that's the version that dropped support for `armv7`.

I'll report this as a bug.

**Comment by jshier** [comment] 2020-06-24 14:51
I've filed FB7764057, so if everyone else seeing this issue could file their own issue and cite this first feedback, we should be able to get this fixed.

**Comment by marcelofabri** [comment] 2020-06-24 16:59
Should we open a report in bugs.swift.org for visibility?

**Comment by jshier** [comment] 2020-06-24 17:11
Is there any way to reproduce the issue without Xcode? I don't think so, as SPM can't build for iOS, so there's no way to see this issue without using Xcode. If that's the case I'm not sure a Swift bug is appropriate. I've request a lab session to discuss the issue with an Apple engineer, so I'll update afterward to see if we need more visibility.

**Comment by dingtianran** [comment] 2020-06-24 20:38
I believe it is a system/beta issue as I saw it building against simulator as well: `outlined init with take of Swift._StringObject.Variant in HTTPHeaders.o ld: symbol(s) not found for architecture i386`

And people discussed this in apple forum: https://developer.apple.com/forums/thread/649918

**Comment by letiendungbk** [comment] 2020-06-26 03:18
We can consider to remove armv7 from all Valid Architectures (main project, pods project) because armv7 is only used for old devices

**Comment by tattn** [comment] 2020-06-29 11:06
I added the workaround to avoid the archive issue (https://github.com/Alamofire/Alamofire/pull/3247)
Please try the following if you use Carthage:
```
github "tattn/Alamofire" "hotfix-xcode12"
```

**Comment by mtangoo** [comment] 2020-06-29 12:04
>I added the workaround to avoid the archive issue (#3247)
Please try the following if you use Carthage:
> github "tattn/Alamofire" "hotfix-xcode12"

This makes the build stage pass!

**Comment by dingtianran** [comment] 2020-07-07 21:54
Encountered this at Xcode 12 beta 2 as well :(

**Comment by dingtianran** [comment] 2020-07-22 20:47
Error persists at Xcode 12 beta 3 (12A8169g)

**Comment by jshier** [comment] 2020-07-22 20:58
I urge everyone who is seeing this issue to file reports with Apple so they can prioritize a fix. Feel free to duplicate my initial report, FB7764057.

**Comment by gbreen12** [comment] 2020-07-22 22:32
How can I file a report with Apple? I've never done that

**Comment by jshier** [comment] 2020-07-22 22:33
@gbreen12 Use the Feedback Assistant app on macOS or follow [these directions](https://developer.apple.com/bug-reporting/).

**Comment by ko7tya** [comment] 2020-07-28 12:30
Increase iOS version in deployment info of alamofire target in Pods project, from 8.0 to 12.0 helps me to resolve this issue

**Comment by HatsuneMikuV** [comment] 2020-07-29 16:57
podfile

`
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end
`

I hope to help you solve the problem

**Comment by jshier** [comment] 2020-07-29 17:33
Yes, any deployment target of iOS 11 and above should avoid the 32-bit compilation issues, as that's the first version that dropped support.

**Comment by gbreen12** [comment] 2020-08-04 20:38
Anyone try this on beta 4 yet?

**Comment by jshier** [comment] 2020-08-04 20:45
I was able to archive the framework using Xcode 12b4, but I'll let one of the other reporters confirm before closing this issue.

**Comment by dingtianran** [comment] 2020-08-04 21:45
🤯
Xcode 12.0 beta 4 (12A8179i) passed, finally

**Comment by gbreen12** [comment] 2020-08-04 22:21
It's still failing for me. I'm using Alamofire in a project with Carthage. Not sure if there is some difference there.

**Comment by jshier** [comment] 2020-08-04 22:22
@gbreen12 Make sure to clear your Carthage dependencies and rebuild with the new version of Xcode.

**Comment by gbreen12** [comment] 2020-08-04 22:44
It's weird I am getting this error:
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/garett/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Alamofire/5.2.2/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework/Alamofire /Users/garett/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Alamofire/5.2.2/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire -output /Users/garett/src/cuwcd/mobilehelpers.data/Carthage/Build/iOS/Alamofire.framework/Alamofire

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/p0/d977974s4vq_3xqjv71sc1gm0000gn/T/carthage-xcodebuild.KMmG6X.log

But when I look at the log file it says it succeeded...

[carthage-xcodebuild.KMmG6X.log](https://github.com/Alamofire/Alamofire/files/5025145/carthage-xcodebuild.KMmG6X.log)

**Comment by jshier** [comment] 2020-08-04 22:45
@gbreen12 Perhaps an issue with Carthage, make sure you're running the latest version.

**Comment by gbreen12** [comment] 2020-08-04 22:57
Looks like it is a problem with Carthage: https://github.com/Carthage/Carthage/issues/3019

I tried to archive the Alamofire project that got downloaded via Carthage and it archived fine so seems like this issue can be closed to me.

**Comment by jshier** [comment] 2020-08-07 16:09
Looks like this is fixed in Xcode 12b4, so I'm closing this issue. Thanks for the input everyone!

**Closed by jshier** 2020-08-07 16:09 UTC
Labels: needs investigation

**Comment by shubhendu-shukla** [comment] 2020-08-24 16:40
I am getting the error while compiling on Xcode 12 beta 5. I am using Carthage

**Comment by jshier** [comment] 2020-08-24 16:41
@shubhendu-shukla You need to rebuild your dependencies using the newer Xcode 12 to see the fix.

**Comment by shubhendu-shukla** [comment] 2020-08-24 18:45
> @shubhendu-shukla You need to rebuild your dependencies using the newer Xcode 12 to see the fix. Additionally, there are Carthage issues with Xcode 12 in general, so you might need to investigate those as well.

I am already compiling with Xcode 12. But Alamofire is breaking while compiling Carthage.

**Comment by jshier** [comment] 2020-08-25 17:20
What error are you getting exactly?

**Comment by shubhendu-shukla** [comment] 2020-08-25 17:24
> What error are you getting exactly?
```

Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/shubhendushukla/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189h/Alamofire/hotfix-xcode12/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework/Alamofire /Users/shubhendushukla/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189h/Alamofire/hotfix-xcode12/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire -output /Users/shubhendushukla/Documents/Carousell-iOS/Carthage/Build/iOS/Alamofire.framework/Alamofire
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/0v/r7qdvvjd4nzf3hh34xdm4l2m0000gn/T/carthage-xcodebuild.FUGEYW.log
make: *** [carthage-install] Error 1
```

**Comment by jshier** [comment] 2020-08-25 17:26
That's not the actual error. You need to read the actual build log to find it. However, that looks like the Carthage error mentioned above, so you should keep track of that issue to see when it's fixed.

**Comment by jbarros35** [comment] 2020-09-18 13:20
it doesn't work anymore. Xcode 12 is official but previous projects won't compile.
