### ISSUE TITLE
carthage update, display error and stop.

### ISSUE THREAD

**Issue by ihugang** [Alamofire/Alamofire#879] opened 2015-10-23 17:42 UTC
Parse error: unexpected SDK key "appletvos"

**Comment by fobin** [comment] 2015-10-23 17:50
Same as here https://github.com/Alamofire/Alamofire/issues/878

**Comment by kylef** [comment] 2015-10-23 18:50
Closed as a duplicate of #878, please search existing issues before opening new ones in the future.

**Closed by kylef** 2015-10-23 18:50 UTC
