### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000 on org.alamofire.session.rootQueue

### ISSUE THREAD

**Issue by yakovmanshin** [Alamofire/Alamofire#3358] opened 2020-11-07 18:47 UTC
## What happened?
I received a Crashlytics alert pointing to crashes on the `org.alamofire.session.rootQueue` queue, in `CFDictionaryGetValue + 20`. The error is `EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000`. The stack trace is below.

According to Crashlytics, the issue has occurred on two devices running iOS 12: one 12.4.1, the other 12.4.6. No crashes have been reported on later versions of iOS, even though they account for the majority of user base.

## What did you expect to happen?
No crashes.

## Alamofire Environment
**Alamofire version:** 5.3.0
**Xcode version:** 12.1
**Swift version:** 5.3
**Platform running Alamofire:** iOS
**macOS version running Xcode:** 10.15.7

## Stack trace for the crashed queue
```
Crashed: org.alamofire.session.rootQueue
0  CoreFoundation                 0x1d0c599dc CFDictionaryGetValue + 20
1  CFNetwork                      0x1d147f360 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.182 + 60
2  Foundation                     0x1d1760cf4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
3  Foundation                     0x1d166cd90 -[NSBlockOperation main] + 72
4  Foundation                     0x1d166c278 -[__NSOperationInternal _start:] + 740
5  Foundation                     0x1d1762a78 __NSOQSchedule_f + 272
6  libdispatch.dylib              0x1d06e77f4 _dispatch_block_async_invoke2 + 104
7  libdispatch.dylib              0x1d07397d4 _dispatch_client_callout + 16
8  libdispatch.dylib              0x1d06e2324 _dispatch_lane_serial_drain$VARIANT$mp + 592
9  libdispatch.dylib              0x1d06e2e40 _dispatch_lane_invoke$VARIANT$mp + 428
10 libdispatch.dylib              0x1d06eb4ac _dispatch_workloop_worker_thread + 596
11 libsystem_pthread.dylib        0x1d091a114 _pthread_wqthread + 304
12 libsystem_pthread.dylib        0x1d091ccd4 start_wqthread + 4
```

The stack traces for both crash events are identical, except for memory addresses.

**Comment by Sunlity** [comment] 2020-11-08 09:22
I got this crash too

**Comment by halinebr** [comment] 2020-11-09 16:47
Receiving several of these crashes

**Comment by jshier** [comment] 2020-11-09 16:48
This is a duplicate of #3326, usually a result of using the Firebase Performance network analytics framework. You need to remove it or update.

**Closed by jshier** 2020-11-09 16:48 UTC
