### ISSUE TITLE
Problems using Swift Package Manager

### ISSUE THREAD

**Issue by patrick-lind** [Alamofire/Alamofire#1582] opened 2016-09-20 14:56 UTC
I'm trying to figure out how to use the SPM and struggling. I understand it's still very early days for it but it appears Alamofire is trying to support it as well so I had a couple issues:

If I try to pull down the master branch and run "swift build" I get:
```
error: the module at Tests/Resources has an invalid name ('Resources'): the name of a test module has no ‘Tests’ suffix
fix: rename the module at ‘Tests/Resources’ to have a ‘Tests’ suffix
```

To get around that for now I just added Tests/Resources to the "exclude" tag in the Package.swift file. When I do that and try "swift build" again I get a lot of error messages similar to:

```
/Alamofire/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
```

I'm thinking when I run "swift build" it's trying to build for all platforms which maybe why I'm seeing these? Everything compiles just fine if I just pull up the original Xcode project. I'm thinking I need to figure out how to define targets in the Package.swift file and regenerate the Xcode project... Anyone else have any experience with this?

**Comment by janekp** [comment] 2016-09-20 17:01
Yes. The Package Manager integration is broken. Also see #1544 that was closed prematurely for some reason.

**Comment by cnoon** [comment] 2016-09-24 23:55
This is a duplicate of #1544. I just commented on that issue as to why the SPM cannot currently compile AF 4.

**Closed by cnoon** 2016-09-24 23:55 UTC
Labels: needs investigation
