### ISSUE TITLE
Status code 401 treated as NSError by default

### ISSUE THREAD

**Issue by virl** [Alamofire/Alamofire#1031] opened 2016-01-27 17:11 UTC
I use Alamofire for Basic Auth with my backend, which returns status code 401 if user is not authorized.

But by default I cannot detect that code on client side, because Alamofire's req.responseData() method returns NSError and response == nil:

```
		req.responseData { (response) -> Void in
			
			if response.result.error != nil {
				log.warning(error?.description)
			}

			if response.response != nil { // Always nil when status == 401
				log.warning("response")
			}
		}
```

How can I retrieve HTTP Status Code from server's response?
I haven't configured any validation, as I understand.

**Comment by virl** [comment] 2016-01-28 13:07
Also when I return another status code from backend (for example, 503 SERVICE_UNAVAILABLE), Alamofire returns it successfully without producing the NSError.

Maybe the bug have something to do with the fact that I use request.authenticate(user: userId!, password: password!) method and Alamofire places additional validation rules with it for 403 code?

**Comment by virl** [comment] 2016-01-29 11:59
@cnoon Any thoughts on this? I really need to access response & header data in case of 401 status code and this bug prevents me from doing that.
There was no such problems with AFNetworking.

**Comment by virl** [comment] 2016-01-29 12:07
Also if I'm not calling request.authenticate() before making the request, I receive 401 status code and response data just fine.

**Comment by virl** [comment] 2016-01-29 17:00
Found workaround by not calling request.authenticate() and instead sending custom Authorization header by constructing new Alamofire.Manager:
```
func updateAlamofire(userId:String?, password:String?) {
		var headers = alamofire.session.configuration.HTTPAdditionalHeaders ?? Alamofire.Manager.defaultHTTPHeaders
		
		if(userId == nil || password == nil) {
			headers.removeValueForKey("Authorization")
		} else {
			let data = "\(userId ?? ""):\(password ?? "")".dataUsingEncoding(NSUTF8StringEncoding)
			let base64Encoded = data?.base64EncodedStringWithOptions(NSDataBase64EncodingOptions(rawValue:0))
			
			headers["Authorization"] = "Basic \(base64Encoded ?? "")"
		}
		
		let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
		configuration.HTTPAdditionalHeaders = headers
		
		self.alamofire = Manager(configuration: configuration)
	}
```

**Comment by cnoon** [comment] 2016-02-04 06:16
Hi @viri, my apologies for not getting back to you sooner. I'm glad you found a workaround. As for your authentication issue, I'm not quite sure what the problem was. You didn't post enough code for me to be sure you weren't making the request wrong. My best guess is that your credentials created by calling the authenticate were failing when the challenge occurred which was triggering the error. However, without some more code to investigate, I can only speculate.

I'm going to close this out for now since you were able to resolve your issue. Cheers. 🍻

**Closed by cnoon** 2016-02-04 06:16 UTC

**Comment by virl** [comment] 2016-02-04 10:32
@cnoon Please re-read the bug description: Alamofire doesn't allow access to response and headers in case when server returns status code 401.

It is not support issue.

**Comment by cnoon** [comment] 2016-02-04 15:09
Alright @viri, could you please post a full code sample (not just the `responseData` closure) and also the error you are seeing? We need more info to go on here.

**Comment by virl** [comment] 2016-02-04 15:26
@cnoon I've already posted it below:
1. Make the request to the server using request.authenticate() method with invalid credentials (so server will return 401 status)
2. You will receive nil response and -999 NSError instead response with headers.

This behaviour even represented in your tests here: https://github.com/Alamofire/Alamofire/blob/master/Tests/AuthenticationTests.swift

See method `testHTTPBasicAuthenticationWithInvalidCredentials()`:
```
func testHTTPBasicAuthenticationWithInvalidCredentials() {
        // Given
        let expectation = expectationWithDescription("\(URLString) 401")

        var request: NSURLRequest?
        var response: NSHTTPURLResponse?
        var data: NSData?
        var error: NSError?

        // When
        Alamofire.request(.GET, URLString)
            .authenticate(user: "invalid", password: "credentials")
            .response { responseRequest, responseResponse, responseData, responseError in
                request = responseRequest
                response = responseResponse
                data = responseData
                error = responseError

                expectation.fulfill()
            }

        waitForExpectationsWithTimeout(timeout, handler: nil)

        // Then
        XCTAssertNotNil(request, "request should not be nil")
        XCTAssertNil(response, "response should be nil")
        XCTAssertNotNil(data, "data should not be nil")
        XCTAssertNotNil(error, "error should not be nil")

        if let code = error?.code {
            XCTAssertEqual(code, -999, "error should be NSURLErrorDomain Code -999 'cancelled'")
        }
    }
```

**Comment by cnoon** [comment] 2016-02-06 20:06
Thanks for all the info here @virl. Now I understand exactly what your concerns are and why you are seeing the behavior you are. This is NOT a bug. This is the exact behavior you should see. What happens when there is an authentication challenge is the following:

* Request is made
* Server sends back authentication challenge for basic auth
* Alamofire provides credentials provided by `authenticate`
* Credentials are sent back to server
* Server rejects credentials and sends back authentication challenge again
* Alamofire cancels the request since authentication has failed
* The request is completed with a cancellation error and no response

There is never a response generated in this scenario, which is why you won't see one when an authentication challenge fails. Hopefully that helps clarify things.

Cheers. 🍻

**Comment by virl** [comment] 2016-02-06 20:24
Ok thanks.
