### ISSUE TITLE
Upload with parameters has a bug in 4.0.1

### ISSUE THREAD

**Issue by kalvish21** [Alamofire/Alamofire#1653] opened 2016-10-01 18:11 UTC
I'm trying to send parameters with uploading an image like so:

    Alamofire.upload(
        multipartFormData: { multipartFormData in
            multipartFormData.append(UIImagePNGRepresentation(tempImage!)!, withName: "file", fileName: "picture.png", mimeType: "image/png")

            // Send parameters
            multipartFormData.append((UserDefaults.standard.value(forKey: Email) as! String).data(using: .utf8)!, withName: "email")
            multipartFormData.append("png".data(using: .utf8)!, withName: "type")

        },
        to: "user/picture",
        encodingCompletion: { encodingResult in
            switch encodingResult {
            case .success(let upload, _, _):
                upload.responseJSON { response in
                    debugPrint("SUCCESS RESPONSE: \(response)")
                }
            case .failure(let encodingError):
                self.removeSpinnerFromView()
                print("ERROR RESPONSE: \(encodingError)")

            }
        }
    )

The send parameters (email and type) are not appearing on my sailsjs server. Is there something I'm doing wrong here? This is what the documentation says?

**Comment by kalvish21** [comment] 2016-10-01 19:54
When I lave out the part where I put:

    multipartFormData.append(UIImagePNGRepresentation(tempImage!)!, withName: "file", fileName: "picture.png", mimeType: "image/png")

THEN the parameters are uploaded. I think this is a bug.

**Comment by cnoon** [comment] 2016-10-01 21:51
Hi @kalvish21,

There's nothing you're missing. You'll need to look at what's going on server-side to troubleshoot. You can also inspect the encoded data by looking at the data blob directly if you manually encode it. You could do that like this:

```swift
let multipartFormData = MultipartFormData()

multipartFormData.append(UIImagePNGRepresentation(tempImage!)!, withName: "file", fileName: "picture.png", mimeType: "image/png")
multipartFormData.append((UserDefaults.standard.value(forKey: Email) as! String).data(using: .utf8)!, withName: "email")
multipartFormData.append("png".data(using: .utf8)!, withName: "type")

do {
    let encodedData = try multipartFormData.encode()
    print(encodedData)
} catch {
    print("Encountered encoding error: \(error)")
}
```

We have all sorts of [tests](https://github.com/Alamofire/Alamofire/blob/master/Tests/MultipartFormDataTests.swift) around this in the Alamofire test suite. I really doubt there's any issue in Alamofire and the issue is server-side.

I'm going to close this issue out for now. If you post more info here that leads us to believe this could be an Alamofire error, we'll happily re-open and investigate further.

Cheers. 🍻

**Closed by cnoon** 2016-10-01 21:51 UTC

**Comment by kalvish21** [comment] 2016-10-01 22:51
I use the same server side code for Alamofire 3.x.x and AFNetworking and it works. The problem is that the "type" and "email" data is not being added. I believe this is a real bug.

**Comment by cnoon** [comment] 2016-10-02 04:03
Could you provide a test demonstrating the behavior?

**Comment by PurviJani** [comment] 2016-10-25 04:51
let imageData = UIImagePNGRepresentation(self.signatureImgView.image!)
        
                let defaultHTTPHeaders: HTTPHeaders =
                               [
                                "token": AFWrapperClass.User_Token,
                               ]
        
                let URL2 = try! URLRequest(url: "http://.....", method: .post, headers: defaultHTTPHeaders)
        
        let multipartFormData = MultipartFormData()

        
        Alamofire.upload(multipartFormData: { (multipartFormData) in
            
            multipartFormData.append(imageData!, withName: "signImg", fileName: "signature.png", mimeType: "image/png")
            
            
//            for (key, value) in self.parameters
//            {
//                multipartFormData.append(value.data(using: String.Encoding.utf8)!, withName: key)
//            }
            }, with: URL2, encodingCompletion: { (result) in
                
                switch result {
                case .success(let upload, _, _):
                    
                    upload.responseJSON
                        {
                            
                        response in
                       
                        print(response.request)  // original URL request
                        print(response.response) // URL response
                        print(response.data)     // server data
                        print(response.result)   // result of response serialization
                       
                        if let JSON = response.result.value
                        {
                            print("JSON: \(JSON)")
                        }
                    }
                    
                case .failure(let encodingError):
                    print(encodingError)
                    
                }
                
        })
    }
  }


it shows error while uploading image please help me.
