### ISSUE TITLE
 No object named "swift-2.0" exists

### ISSUE THREAD

**Issue by imns** [Alamofire/Alamofire#758] opened 2015-09-11 00:11 UTC
Probably a noob issue, but I created a Cartfile and added `github "Alamofire/Alamofire" "swift-2.0" ` to it.  When I run  `carthage update` I get the error:  `Failed to check out repository into  Users/myuser/Library/Caches/org.carthage.CarthageKit/dependencies/Alamofire: No object named "swift-2.0" exists `

**Comment by keith** [comment] 2015-09-11 00:34
Duplicate of https://github.com/Alamofire/Alamofire/issues/749

**Closed** 2015-09-11 03:23 UTC

**Comment by kylef** [comment] 2015-09-11 03:25
Not actually a duplicate, this is for Carthage not CocoaPods. #759 fixes this.

@imns Please use the following in your Cartfile:

```odgl
github "Alamofire/Alamofire" ~> 2.0
```
