### ISSUE TITLE
SessionDelegate crash when downloading a file

### ISSUE THREAD

**Issue by mbarashkov** [Alamofire/Alamofire#3293] opened 2020-09-02 12:56 UTC
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Our users reported several crashes which originated in SessionDelegate.swift: 302
`fatalError("URLSessionDownloadTask finished downloading with no response.")`
Apparently that happened when request.response was nil

## What did you expect to happen?
I expected Alamofire not to crash the entire app, instead, return error to the file download caller.
Also, I don't understand why in this area of code Alamofire needs request.response at all. It seems like it could be safely deleted.

## What happened
The app crashed

## Alamofire Environment

**Alamofire version:*5.2.2*
**Xcode version:*11.7*
**Swift version:*5.2*
**Platform(s) running Alamofire:*iOS*
**macOS version running Xcode:*10.15.6*

## Demo Project

Can't provide a Demo Project.

**Comment by jshier** [comment] 2020-09-02 17:51
A `response` is required there because that's how Alamofire's download location APIs work. It's not possible for `URLSessionDownloadTask`s to finish without one, so the assertion ensures the world isn't broken. 

How are you downloading files? Are you using resume data? Are you using any sort of network analytics framework that might be interfering with the proper delegate callbacks? Are you trying to use a background `URLSessionConfiguration`?

**Comment by mbarashkov** [comment] 2020-09-03 07:44
@jshier 
We are not using resume data or network analytics, or a background configuration. Downloads are very simple:
`
ServerAPIBase.APIManager.sharedManager.download(url, to: destination).response { response in
                if response.error == nil, let downloadPath = response.fileURL?.path {
                    completion(downloadPath)
                } else {
                    let error = response.error?.underlyingError as? URLError
                    let offline = error?.code == URLError.Code.notConnectedToInternet || error?.code == URLError.Code.timedOut
                    failure(offline)
                }
            }
`
(ServerAPIBase.APIManager.sharedManager is:
`
static let sharedManager: Alamofire.Session = {
            if APIManager._sharedManager != nil {
                return APIManager._sharedManager!
            }
            let configuration = URLSessionConfiguration.default
            configuration.timeoutIntervalForRequest = 15
            APIManager._sharedManager = Alamofire.Session(configuration: configuration)
            return APIManager._sharedManager!
         }()
`

Also, I can understand that download failed, ok. But why should it crash the entire app with a fatalError?

**Comment by jshier** [comment] 2020-09-03 14:35
The fatal error isn't due to a download failure, as that delegate method is only called when the request completes successfully and the file is downloaded. At that point it must have a `response`, so let me take a deeper look at ordering.

**Comment by jshier** [comment] 2020-10-03 21:54
@mbarashkov It appears this crash can be caused by downloading a `file://` `URL`, which is supported by `URLSessionDownloadTask`. Do you have a particular use for this functionality? Otherwise I'm tempted to just produce an error when attempting to download file URL.

**Comment by jshier** [comment] 2020-10-18 01:43
This should now be fixed in 5.3.0. Attempting to request a `file://` `URL` will now produce a validation error rather than a crash. If a compelling use case exists for supporting `file` `URL`s I can investigate adding proper support in the future, though it would be a major change and thus only be part of Alamofire 6 or later.

**Closed by jshier** 2020-10-18 01:43 UTC
Labels: needs investigation

**Comment by jshier** [comment] 2020-11-04 21:42
The error that was added has been removed in 5.4.0 and full support has been restored. `DownloadRequest` can now be used with `file://` URLs, but the `Destination` is not respected due to the required `HTTPURLResponse`.
