### ISSUE TITLE
Increased number of crashes being reported

### ISSUE THREAD

**Issue by LucasAssisRo** [Alamofire/Alamofire#3357] opened 2020-11-06 08:16 UTC
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I noticed a significant increase of crashes coming from `Alamofire.Session` after updating from version 5.1 to version 5.4.
The crash logs point to the method `updateStatesForTask(_ task: URLSessionTask, request: Request)` and indicate a heap corruption.

```
Crashed: org.alamofire.session.rootQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000dc52e2890
```

## Alamofire Environment

**Alamofire version:** 5.4
**Xcode version:** 12.1
**Swift version:** 5
**Platform(s) running Alamofire:** iOS 12/13/14
**macOS version running Xcode:** 10.15.7

**Comment by AtharvaVaidya** [comment] 2020-11-06 13:06
+1

**Comment by jshier** [comment] 2020-11-06 18:06
This is likely a duplicate of #3326. It's caused by Firebase Performance or another network performance analytics framework. You'll need to remove or upgrade those frameworks.

**Closed by jshier** 2020-11-06 18:06 UTC
