### ISSUE TITLE
unable to build watchOS target because Bitcode is disabled?

### ISSUE THREAD

**Issue by jurvis** [Alamofire/Alamofire#689] opened 2015-08-15 04:37 UTC
I've been unable to build Alamofire on carthage which produces the following error in the log:

```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO

=== BUILD TARGET Alamofire OSX OF PROJECT Alamofire WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

Write auxiliary files
write-file /Users/jurvistan/Library/Developer/Xcode/DerivedData/Alamofire-giuxdschbqsymscojpimobtahmgq/Build/Intermediates/Alamofire.build/all-product-headers.yaml

=== BUILD TARGET Alamofire OSX Tests OF PROJECT Alamofire WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchos2.0

=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

Write auxiliary files
write-file /Users/jurvistan/Library/Developer/Xcode/DerivedData/Alamofire-giuxdschbqsymscojpimobtahmgq/Build/Intermediates/Alamofire.build/all-product-headers.yaml

** BUILD SUCCEEDED **

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
target 'Alamofire watchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform
```

If Bitcode is compulsory for watchOS, shouldn't it be enabled for the watchOS target by default?

Thanks!

**Comment by cnoon** [comment] 2015-08-15 19:11
Bitcode is enabled in both Debug and Release configurations for the watchOS target in the `swift-2.0` branch. I just built Alamofire on all three OS's using Carthage without any issues.

### Cartfile

```bash
github "Alamofire/Alamofire" "swift-2.0"
```

### Carthage Version

```bash
cnoon:~/Desktop/CarthageChecker$ carthage version
0.8.0
```

### `xcodebuild` version

```bash
cnoon:~/Desktop/CarthageChecker$ xcodebuild -version
Xcode 7.0
Build version 7A176x
```

### `carthage update` output

```bash
cnoon:~/Desktop/CarthageChecker$ carthage update
*** Fetching Alamofire
*** Checking out Alamofire at "9a1e321cf0a345b32142394446fa1a7e08cf6942"
*** xcodebuild output can be found in /var/folders/s7/qpm0b2pn3d56rjlpl7g3_4fh0000gn/T/carthage-xcodebuild.zLOTLA.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
```

If you continue to experience issues, I would suggest opening an issue with the Carthage project.

**Comment by Sljux** [comment] 2015-09-22 11:10
"swift-2.0" branch seems to be merged to master, but this problem persists.

# Cartfile
`github "Alamofire/Alamofire"`

# Carthage Version
```
Sljux:Documents Sljux$ carthage version
0.8.0
```

# `xcodebuild` version
```
Sljux:Documents Sljux$ xcodebuild -version
Xcode 7.0
Build version 7A218
```

# `carthage update` output
```
Sljux:Documents Sljux$ carthage update
*** Fetching Alamofire
*** Checking out Alamofire at "2.0.2"
*** xcodebuild output can be found in /var/folders/td/99svwd2x5b3g6nkwjv_3y52w0000gn/T/carthage-xcodebuild.kYUE0x.log
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

# Log file
```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchos2.0

=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET Alamofire watchOS OF PROJECT Alamofire WITH CONFIGURATION Release ===

Check dependencies
target 'Alamofire watchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform
```

**Comment by cnoon** [comment] 2015-09-23 04:59
Hi @Sljux, I just filed [Carthage 790](https://github.com/Carthage/Carthage/issues/790) which hopefully will help resolve the issue. I was able to reproduce the behavior you're seeing.

**Comment by cnoon** [comment] 2015-09-27 18:54
It appears that you MUST have an iPhone + watch simulator set up in Xcode before you can use Carthage to compile the Alamofire watchOS framework. Not entirely sure why, but at least know we know how to solve the problem.

Please refer to [Carthage #790](https://github.com/Carthage/Carthage/issues/790) issue for more details.

**Closed by cnoon** 2015-09-27 18:54 UTC
Labels: carthage, project config
