### ISSUE TITLE
Bundle Identifier does not match

### ISSUE THREAD

**Issue by thomasMinshull** [Alamofire/Alamofire#2938] opened 2019-09-06 22:09 UTC
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I ran `carthage update --platform iOS`

In my Cartfile, I have `github "Alamofire/Alamofire" ~> 4.8`
The terminal response included `*** Checking out Alamofire at "4.9.0"`

Everything appeared to work normally until I archived the application and validated the build prior to submitting it to the app store. 

## What did you expect to happen?

I expected the build to be validated and to be able to submit it to the app store

## What happened instead?

I received the following error:

App Store Connect Operation Error
Invalid Code Signature Identifier. The identifier "org.alamofire.Alamofire.iphoneos" in your code signature for "Alamofire" must match its Bundle Identifier "org.alamofire.Alamofire" 

## Alamofire Environment

**Alamofire version:** 4.9.0
**Xcode version:** 10.2 
**Swift version:** 4.2 
**Platform(s) running Alamofire:** iOS 
**macOS version running Xcode:** N/A

**Comment by jshier** [comment] 2019-09-06 22:43
I don't see a separate setting for these identifiers, so you might be able to fix it by deleting your Carthage checkout and rebuilding.

**Comment by thomasMinshull** [comment] 2019-09-06 23:15
I tried deleting my Carthage directory and that didn't seem to solve the issue. 

I've fixed the issue for now, by pinning to 4.8.2.

**Comment by jshier** [comment] 2019-09-07 20:43
@thomasMinshull All of the fixes I can find for an issue like this point to an Xcode issue. Can you try restarting Xcode, clearing your derived data, clearing your Carthage checkouts, and building again?You can also try removing Alamofire and readding it from Carthage. There seems to be some cached expectation for the old identifier in Xcode which can cause this.

**Comment by zizi4n5** [comment] 2019-09-30 04:20
I'm having trouble with the same problem.
The cause seems to be the following PR, but I do not know how to solve it.

https://github.com/Alamofire/Alamofire/pull/2930

**Comment by zizi4n5** [comment] 2019-10-02 01:14
I'm sorry. The problem was due to us not running copy-frameworks.
By running copy-frameworks, we confirmed that the problem no longer occurs in 4.9.0.
Even if we didn't run copy-frameworks, there was no problem until 4.8.2.
However, it seems that the potential problem has been revealed by switching Bundle ID for each platform in correspondence with https://github.com/Alamofire/Alamofire/pull/2930 of 4.9.0.

**Comment by maxx-cyber** [comment] 2019-10-11 17:20
I have similar issue. Issue is reproduced on fresh machine, without any cached derived data, etc.

ERROR ITMS-90334: "Invalid Code Signature Identifier. The identifier "org.alamofire.Alamofire.iphonesimulator" in your code signature for "Alamofire" must match its Bundle Identifier "org.alamofire.Alamofire.iphoneos""

**Comment by jshier** [comment] 2019-10-11 17:22
Are you using a precompiled version from Carthage or something?

In any case, this doesn't seem to be a reliable fix, so I may just revert it and only make the watchOS target have a different identifier, since that's the only conflict we can have.

**Comment by maxx-cyber** [comment] 2019-10-11 17:35
I have `github "Alamofire/Alamofire" ~> 4.8.2` in Cartfile and precompiled version 4.8.2. Today I start migration to Xcode 11 and have to rebuild Alamofire. I deleted whole Carthage folder and Carthage.resolved file and perform Carthage update to rebuild it with Xcode 11. Carthage.resolved now contains 4.9.0. Then I performed archive, export archive and upload build to App Store Connect. All as usual with the same script. But now I receive mentioned ITMS error.
Seems adding `${PLATFORM_NAME}` was not good idea. I think it is better to add just `watchOS` for watchOS bundle identifier. By the way, to avoid https://github.com/Alamofire/Alamofire/pull/2930 issue I add `watchOS` to watch bundle identifier in build script phase of watch kit extension target and all works fine. So if you revert `${PLATFORM_NAME}` and just add `watchOS` to watchOS bundle identifier, I can remove my hack in build script phase.

**Comment by jshier** [comment] 2019-10-11 17:37
Sounds good. I'll try to get new versions out this weekend.

**Comment by jjlopez87** [comment] 2019-10-18 11:33
You have to change in Alamofire project the bundle identifier 'org.alamofire.Alamofire.${PLATFORM_NAME}' to 'org.alamofire.Alamofire' in project.pbxproj and build again: carthage update --platform iOS.

PRODUCT_BUNDLE_IDENTIFIER = org.alamofire.Alamofire;

**Comment by jshier** [comment] 2019-10-22 00:00
I've merged the fix into the `hotfix` (for v4) and `master` branches if anyone wants to try them out. I hope to get releases out soon.

**Comment by maxx-cyber** [comment] 2019-10-22 09:12
Thanks @jshier 
Currently I stay on version 4.8.2 with my workaround (adding WatchOS to bundle identifier in build script phase) and waiting for release 4.9.1 with your fix.
By the away, are there any critical fixes in 4.9.0 compared with 4.8.2? Can I stay on 4.8.2 or updating to 4.9.x is strongly recommended?

**Comment by jshier** [comment] 2019-11-04 04:45
This should be resolved in 4.9.1. @maxx-cyber 4.9.0 also included a thread-safety fix for validators, but you can check our CHANGELOG to see if any of the changes are relevant to you.

**Closed by jshier** 2019-11-04 04:45 UTC
Labels: needs feedback
