### ISSUE TITLE
Alamofire shows warning when setting deployment target to 9.0

### ISSUE THREAD

**Issue by NuelNikhil** [Alamofire/Alamofire#871] opened 2015-10-19 06:42 UTC
I am trying to using Alamofire in my project , i have downloaded the latest file from Github and added the framework to my project. Then i came to Read that we need to set the Deployment target of Alamofire to same as our project deployment Target. My project Deployment target is 9.0 and when i set the Deployment Target of Alamofire to 9.0 it throws a warning

>Unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true 

I am Using **Mac OS X Yosemite Version: 10.10.5**
**Xcode Version 7.0 ,**
**Swift 2**
**Alamofire Version : 3.0.0**
 Downloaded from https://github.com/Alamofire/Alamofire

**Comment by cnoon** [comment] 2015-10-20 02:09
How did you add Alamofire to your project? Did you use CocoaPods, Carthage or manual installation by downloading the source and adding the Alamofire Xcode project as a dependency to your project?

**Comment by sendoa** [comment] 2015-10-20 05:14
I have the same "issue". I added Alamofire through Cocoapods.

**Comment by cnoon** [comment] 2015-10-20 06:10
Yeah I don't really know if there's a workaround for this particular issue. The availability methods are a bit annoying in this respect. The problem is that they need to be included in the project to get everything to compile with a deployment target of iOS 8.0. When you install using CocoaPods with a deployment target of 9.0, the availability methods will trip the warning.

I'll think on this some more and possibly file a radar. If anyone has any suggestions in the community on a way to get around this while maintaining an iOS 8 deployment target, I'm all ears!

**Comment by sendoa** [comment] 2015-10-20 07:40
By the way, I enabled `inhibit_all_warnings!` in the `Podfile` but the warning remains.

**Comment by NuelNikhil** [comment] 2015-10-20 13:35
I have Added Alamofire manually.

**Comment by cnoon** [comment] 2015-10-22 01:49
cc @kylef to see if there's any magic he knows of to workaround this problem.

**Comment by kylef** [comment] 2015-10-22 01:55
I don't know of the top of my head.

@sendoa I'd suggest filing a bug on CocoaPod's if there ware warnings that are not being inhabited by `inhibit_all_warnings!`. There might be something we can do, but this may be an Apple bug and may need to be raised further upstream as a radar if the bug lies with Apple.

**Comment by cnoon** [comment] 2015-10-22 02:04
Thanks for the feedback @kylef. I assumed this was actually an Apple bug and we'd need to file a radar. This will make the 3rd or 4th radar I've filed around availability so I'm not surprised. Once I get it filed, I'll post the link to Open Radar and close this issue out.

**Comment by cnoon** [comment] 2015-10-25 20:55
Thank you for filing [CocoaPods #4423](https://github.com/CocoaPods/CocoaPods/issues/4423) @sendoa. I've added additional comments about a [sample project](https://github.com/cnoon/AvailabilityWarningRadar) I created to demonstrate the problem. Hopefully we can get this issue resolved for all Pod libraries. 

Given that this is not actually an issue with Alamofire that we can solve, I'm going to close this issue out. I will update this issue periodically as we learn more about 4423.

**Comment by cnoon** [comment] 2015-10-25 20:56
On second thought, I think I'll leave this one open until we get a confirmation from the CocoaPods team as to how they want to proceed.

**Comment by kylef** [comment] 2015-10-25 21:00
Yes, and for tracking purposes there is a PR at https://github.com/CocoaPods/CocoaPods/pull/4320 which would solve this.

**Comment by segiddins** [comment] 2015-10-31 20:20
The aforementioned CocoaPods PR has now been merged.

**Comment by cnoon** [comment] 2015-10-31 21:06
Awesome! Thanks @segiddins.

**Closed by cnoon** 2015-10-31 21:06 UTC
Labels: blocked, cocoapods

**Comment by muhasturk** [comment] 2015-11-21 14:50
I still get when I build project

```
Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true
```
![](http://i.imgur.com/exnePui.png)

➜  Smart Citizen git:(develop) ✗ pod --version
0.39.0
OSX El Capitan 10.11.1
Xcode Version 7.1.1 (7B1005)
Alamofire 3.1.2

**Comment by cnoon** [comment] 2015-11-22 20:45
Yep, that change is not part of CocoaPods 0.39.0. It will be available in the next pre-release.

**Comment by muhasturk** [comment] 2015-11-22 20:55
Thank you for reply.

**Comment by pavankataria** [comment] 2015-12-29 03:34
@cnoon is it ok to grab the development branch of alamofire for development? How long till the next pre-release?

**Comment by kylef** [comment] 2016-01-02 19:46
@pavankataria The next pre-release of CocoaPods, as this is a CocoaPods bug not Alamofire. CocoaPods 1.0.0.beta.1 contains the fix and can be installed via:

```shell
$ gem install cocoapods -v 1.0.0.beta.1
```

**Comment by adamwaite** [comment] 2016-01-03 17:14
Yeah that's fixed it @kylef, thanks

**Comment by KamalHunzai** [comment] 2016-02-18 11:51
I built my project using Xcode 7.2.1 (7C1002) and deployment target iOS 9 at the first place. Later i need to deployment target to be set at iOS 8. 
My issues was similar to this one and the fixed didn't work:
http://stackoverflow.com/questions/32692828/module-files-deployment-target-is-ios9-0-v9-0-with-xcode-7-swift-2

Fix:
I closed the project and updated my pod. 

Huraah! it's working fine now
