### ISSUE TITLE
Calling `DownloadRequest.cancel(producingResumeData: false)` will produce resume data in the tmp folder.

### ISSUE THREAD

**Issue by hayama-junpei** [Alamofire/Alamofire#3536] opened 2022-01-05 07:38 UTC
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

After calling `Session.download(...)` to start the download, I called the `cancel ()` method of the return value `DownloadRequest`.

## What did you expect to happen?

I expected the download would be canceled without creating the resume data in the tmp folder.

## What happened instead?

A file like `CFNetworkDownload_*.tmp` was created in the tmp folder. 

## Alamofire Environment

**Alamofire Version:** 5.4.4
**Dependency Manager:** CocoaPods
**Xcode Version:** 13.2.1 (13C100)
**Swift Version:** 5.5.2
**Platform(s) Running Alamofire:** iPadOS 15.2
**macOS Version Running Xcode:** 12.1（21C52）

## Supplementary information

This feature was proposed in issue #2841 and added in PR #2851. However, it seems that this feature does not work properly due to the fix of PR #3102.

Comment from PR #3102: 

> Additionally, DownloadRequests are now always cancelled with cancel(producingResumeData:), as asynchronous cancellation with cancel() does not work. (Apple bug pending.)

I tried the `URLSessionDownloadTask.cancel()` method and it seemed to work now. 
It was able to cancel the download without creating resume data in the tmp folder.

(What was the bug in the `cancel()` method?)

**Comment by jshier** [comment] 2022-01-08 07:29
Yes, the behavior was reverted for Alamofire 5 due to a bug in iOS versions before 14 (FB7619240) where calling `task.cancel()` asynchronously would fail to fire the expected metrics gathering delegate methods (as well as other internal `URLSession` events. Since Alamofire relies on those methods to gather metrics and finish the request, we had to work around the bug by always calling `cancel(byProducingResumeData:)`. 

That said, resume data isn't written to disk unless you write it to disk. By default, the method simply returns any resume `Data` that's available and it's up to you to do what you want with it. By default, if Alamofire receives resume data it will attach it to the `DownloadResponse`. In the cancellation case, we don't handle the data all and just pass an empty closure, so the value is just dropped. 

Ultimately, the `CFNetworkDownload_*.tmp` file you see is the data downloaded before cancellation, not the resume data (which is just metadata to help resume the download, not the actual downloaded data, which remains on disk). However, I did confirm that when calling `cancel(byProducingResumeData:)` this temporary file isn't automatically deleted like it is when just calling `cancel()`. I'll investigate what we can do, but I'm rather against reverse engineering the resume data format, as it's proprietary, can change over time, and has been broken in the past. Perhaps for iOS >= 14 we can go back to using `cancel()` and older systems will just have to deal with the extra data on disk until the temp directory is cleared.

**Comment by jshier** [comment] 2022-01-08 08:03
I've opened #3538 which fixes this on newer OSes. I think that's about as good as we can do.

**Comment by hayama-junpei** [comment] 2022-01-11 09:28
Thank you for investigating and creating the pull request.
That pull request looks good to me.
(It would be even better if the same changes were applied to iOS 12 and 13.)

> Ultimately, the CFNetworkDownload_*.tmp file you see is the data downloaded before cancellation, not the resume data (which is just metadata to help resume the download, not the actual downloaded data, which remains on disk).

Yes, the expression of the title of pull request was not good.
However, resume is a function that resumes downloading from the interrupted byte position, so I think it is necessary for `cancel(producingResumeData:)` to leave a temporary file of downloaded data. ( https://developer.apple.com/documentation/foundation/urlsessiondownloadtask/1411634-cancel )

The problem for me was that CFNetworkDownload_ * .tmp contained the pre-cancelled download data, so the file size was large.
Files in temporary folders are not deleted while the application is active. As a result, the problem was that the storage usage increased by repeatedly canceling downloads could not be resolved while the application was active.

I think that the above problem can be solved with the newer ios by the pull request, so I'm waiting for the merge and release.

Best regards.

**Comment by jshier** [comment] 2022-01-18 00:25
@hayama-junpei After further investigation it appears that the underlying bug was a regression in iOS 13 that was fixed in iOS 14 and so only affect the one OS version. At the least it seems we can fix this for everything but iOS 13 (and that year of Apple OSes). 

I've also been investigating whether it's necessary for us to use this workaround at all now and haven't been able to create a failing test, even when using the same methodology in my original bug report that still fails on iOS 13. So we may be able to remove the behavior generally.

**Comment by jshier** [comment] 2022-01-30 04:01
Merged #3538 to revert the previous change. Now that we have older OS test coverage I feel confident that Alamofire's cancellation doesn't trigger the bug on older OSes. Thanks!

**Closed by jshier** 2022-01-30 04:01 UTC
Labels: needs investigation

**Comment by hayama-junpei** [comment] 2022-01-31 01:45
@jshier Thank you for the investigation and fix!
