### ISSUE TITLE
Validation errors do not provide any information

### ISSUE THREAD

**Issue by berikv** [Alamofire/Alamofire#528] opened 2015-06-15 10:35 UTC
For any validation, the error reported to the handler is:

    NSError(domain: AlamofireErrorDomain, code: -1, userInfo: nil)

When using validation together with responseJSON (for example) the failure reason is unknown to the response handling block. This causes the validation to be duplicated when handling the error:

    let request = Alamofire.request(method, url, parameters: parameters, encoding: encoding)
        .validate(statusCode: 200..<300)
        .responseJSON { request, response, json, error in
            if contains(200..<300, response.statusCode) { ... }

Also, the response data is not available to the handler block in case of a validation error.

**Comment by cnoon** [comment] 2015-06-16 14:57
Thanks for your feedback @berikv. This issue is a duplicate of #447 and I'm going to close it out as such. This is something we're planning on addressing in the 2.0.0 release.

For now, you can simply key off the domain and `-1` code if you like since validation is the only step that throws such an error.

**Closed by cnoon** 2015-06-16 14:57 UTC
Labels: duplicate
