### ISSUE TITLE
App crashes immediately on iOS 12.4.1 after upgrading Alamofire to 5.5.0

### ISSUE THREAD

**Issue by larsriehn** [Alamofire/Alamofire#3586] opened 2022-04-08 13:07 UTC
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

In our APP we upgraded the Alamofire pod from 5.4.3 to 5.5.0.
We build the APP through our regular pipeline for a distribution through Firebase (to test the new features).

## What did you expect to happen?

I expect the APP to run on iOS devices from iOS 12 to iOS 15. 

## What happened instead?

The APP crashes immediately on iOS 12.4.1 (probably on all versions iOS 12.x)
It runs on all iOS Versions we could test from iOS 14 to 15.
The crash definitely comes from upgrading Alamofire.
The crash does not happen in the simulator, only on real devices.

## Alamofire Environment

**Alamofire Version:**5.5.0 (update from 5.4.3)
**Dependency Manager:**Cocoapods 1.11.2
**Xcode Version:** Xcode 13.2.1
**Swift Version:** 5
**Platform(s) Running Alamofire:** iOS 12.4.1
**macOS Version Running Xcode:** 11

**fastlane Version:** 2.196.0

## Demo Project

n.a.

**Comment by jshier** [comment] 2022-04-08 15:06
This is a duplicate of #3529. If you can upgrade to Xcode 13.3, the crashes should be fixed but you'll need to disable BitCode. Alternatively, stay on Alamofire 5.4.4 until Apple ships a fix or we separate out the concurrency APIs.

**Closed by jshier** 2022-04-08 15:06 UTC
