### ISSUE TITLE
Crash on ResponseSerialization.swift line 151

### ISSUE THREAD

**Issue by nourSh** [Alamofire/Alamofire#3017] opened 2019-12-12 09:23 UTC
We have faced the following crash & we didn't have steps for it. 

<img width="1106" alt="Screen Shot 2019-12-12 at 11 20 53 AM" src="https://user-images.githubusercontent.com/3489494/70699406-be059180-1cd1-11ea-8bdf-1351cc795033.png">

## Alamofire Environment
**Alamofire version: 4.9.0
**Xcode version: 10.3
**Swift version: 4
**Platform(s) running Alamofire: iOS

**Comment by jshier** [comment] 2019-12-14 06:10
Can you post your response serializer usage? This is most likely due to the content of your completion handler, not an issue with Alamofire.

**Comment by nourSh** [comment] 2019-12-29 16:11
@jshier, unfortunately, we didn't know how this crash happened, so we couldn't know what is the response that returns from the API when this crash happened.

**Comment by jshier** [comment] 2019-12-31 01:52
I meant, what's the code you run in your response serializer, not the content of the response you receive. This crash is most likely caused by something in your response handler, so if you post it I may be able to point it out for you.

**Comment by jshier** [comment] 2020-01-27 01:46
I'm closing this issue. If you need further help, StackOverflow may help diagnose the crash, otherwise you can reply to this issue with more details.

**Closed by jshier** 2020-01-27 01:46 UTC
Labels: needs feedback

**Comment by nourSh** [comment] 2020-01-28 13:45
@jshier sorry for being late, 

here is the code that we use:
`
let manager = Alamofire.SessionManager.default
        manager.session.configuration.timeoutIntervalForRequest = 120

        let forBiddenReqQueue = DispatchQueue(label: "forbiddenQueue")
        let requestQueue = DispatchQueue(label: "......response-queue", qos: .utility, attributes: [.concurrent])

        currentRequest = manager.request(finalUrl, method: httpMethod, parameters: params, encoding: encoding, headers: headers).responseJSON(queue: requestQueue, options: .allowFragments) { (res) in
....... 
}
`

**Comment by nourSh** [comment] 2020-02-10 21:57
> I'm closing this issue. If you need further help, StackOverflow may help diagnose the crash, otherwise you can reply to this issue with more details.

@jshier Could you please check my comment

**Comment by jshier** [comment] 2020-02-10 22:09
There are several issues with the code you posted.

1. It's not the response handler code previously asked for, so it doesn't do anything to help with the cause of the crash, unless it's caused by one the other issues I'm noting here.
2. Setting a `URLSessionConfiguration` property on a configuration that's already be added to a `URLSession`, as the one you're attempting to set `timeoutIntervalForRequest` on, has no affect, so it's not doing what you need.
3. If you need to use a custom queue for your response handlers, it's best to use a serial queue, not a concurrent one, unless you're certain of the scaling and thread safety of the actions in your completion handler.
4. Depending on the work in your response handler, you probably don't need to a custom queue in the handler. That queue is only used for the completion handler closure, not for the request itself, which, by the name, I'm guessing was your intention. By default completion handlers are called on the main queue while all of the work performed by a request is performed on a background queue. Unless you have a good reason for the custom queue, it shouldn't be necessary.

So ultimately, it's still not clear what's causing this crash. Most likely there's something in your response handler that is causing it, but whether it's a code issue or a queuing issue is unclear. I suggest you run with the thread sanitizer and main queue sanitizer active and see if they turn up any issues. Also, avoiding force unwrapping and other unsafe behaviors may help.

**Comment by nourSh** [comment] 2020-02-10 22:18
@jshier Thank you, I will check this with the team, and get back to you.
