### ISSUE TITLE
Crash org.alamofire.session.rootQueue EXC_BAD_ACCESS KERN_PROTECTION_FAILURE NSKeyValueWillChange

### ISSUE THREAD

**Issue by SherifKamalSalem** [Alamofire/Alamofire#3348] opened 2020-10-29 07:57 UTC
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you expect to happen?

ℹ work normally.  

## What happened instead?

ℹ com.apple.main-thread
0  libsystem_malloc.dylib         0x19321de00 nanov2_pointer_size + 220
1  libsystem_malloc.dylib         0x19321e3f0 nanov2_free + 60
2  CoreFoundation                 0x18412543c _CFRelease + 1004
3  CoreFoundation                 0x18408c8dc -[__NSDictionaryI dealloc] + 156
4  CFNetwork                      0x1849f1228 __CFTubeSetTubeTypeNotifier + 64912
5  CFNetwork                      0x18479a274 (Missing)
6  libswiftCore.dylib             0x18800880c swift_arrayDestroy + 128
7  libswiftCore.dylib             0x187d3181c _ContiguousArrayStorage.__deallocating_deinit + 84
8  libswiftCore.dylib             0x1880145a4 _swift_release_dealloc + 40
9  Alamofire                      0x1073a9dac destroy for Request.MutableState + 4414758316 (<compiler-generated>:4414758316)
10 Alamofire                      0x10737c038 Protected.deinit + 113 (Protected.swift:113)
11 Alamofire                      0x10737c06c Protected.__deallocating_deinit + 113 (Protected.swift:113)
12 libswiftCore.dylib             0x1880145a4 _swift_release_dealloc + 40
13 Alamofire                      0x107390238 Request.deinit + 29 (Request.swift:29)
14 Alamofire                      0x10739466c DataRequest.deinit + 981 (Request.swift:981)
15 Alamofire                      0x1073946cc DataRequest.__deallocating_deinit + 981 (Request.swift:981)
16 libswiftCore.dylib             0x1880145a4 _swift_release_dealloc + 40
17 libswiftCore.dylib             0x1880153f4 bool swift::RefCounts<swift::SideTableRefCountBits>::doDecrement<(swift::PerformDeinit)1>(unsigned int) + 276
18 Alamofire                      0x10733b008 outlined init with copy of DataResponse<Data?, AFError> + 4414304264 (<compiler-generated>:4414304264)
19 libswiftCore.dylib             0x1880145a4 _swift_release_dealloc + 40
20 Alamofire                      0x10734fcbc outlined init with copy of EventMonitor + 4414389436 (<compiler-generated>:4414389436)
21 libswiftCore.dylib             0x1880145a4 _swift_release_dealloc + 40
22 Alamofire                      0x10734fd54 block_destroy_helper.119 + 4414389588 (<compiler-generated>:4414389588)
23 libsystem_blocks.dylib         0x1cc02b794 _Block_release + 200
24 libdispatch.dylib              0x183da4ac8 _dispatch_client_callout + 20
25 libdispatch.dylib              0x183db204c _dispatch_main_queue_callback_4CF + 836
26 CoreFoundation                 0x1841231e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
27 CoreFoundation                 0x18411d3b4 __CFRunLoopRun + 2508
28 CoreFoundation                 0x18411c4bc CFRunLoopRunSpecific + 600
29 GraphicsServices               0x19ac2e820 GSEventRunModal + 164
30 UIKitCore                      0x186ac9164 -[UIApplication _run] + 1072
31 UIKitCore                      0x186ace840 UIApplicationMain + 168
32                      0x104d74070 main + 22 (AppDelegate.swift:22)
33 libdyld.dylib                  0x183de3e40 start + 4.  

## Alamofire Environment

**5.3.0**
**Xcode 12:**
**latest:**
**iOS:**
**macOS version running Xcode:**

**Comment by jshier** [comment] 2020-10-29 14:19
This is a duplicate of #3326. As you can read in that thread, particular versions of the Firebase Performance framework can cause this crash, so you need to update or remove it.

**Closed by jshier** 2020-10-29 14:19 UTC

**Comment by mahesh-rideziro** [comment] 2020-11-24 11:57
I am getting the same error. please suggest me for solution
<img width="540" alt="Screen Shot 2020-11-24 at 3 56 48 PM" src="https://user-images.githubusercontent.com/63711110/100091233-c799f200-2e6d-11eb-9bbb-68fdab868dc3.png">
<img width="497" alt="Screen Shot 2020-11-24 at 3 56 40 PM" src="https://user-images.githubusercontent.com/63711110/100091240-c9fc4c00-2e6d-11eb-9761-8197086e8943.png">

**Comment by Grigor55** [comment] 2022-12-21 07:16
Hello.
Do you understand why crashes?
I also getting this crash
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x000000016b4dffe0
