### ISSUE TITLE
Allow default delegation in SessionDelegate (with attached pr)

### ISSUE THREAD

**Issue by taquitos** [Alamofire/Alamofire#1145] opened 2016-03-28 23:54 UTC
By default, the session delegate executes a delegate block property if it exists and then stops. I would like to be able to set various delegate closure properties that get executed but also continue with default handling. I need to be notified of a few methods being called (along with their args), but I want the default behavior to continue. I have a PR on a forked Alamofire open: https://github.com/taquitos/Alamofire/pull/1/files

I'm open to suggestions on how to accomplish, or make it better. I know that it isn't perfect as we can't add this feature to every delegate callback (because some require completion blocks to be called as part of the delegate callback), but I think keeping clear documentation and comments is the best solution.

Note: I didn't include unit tests yet as I'd like to make sure this approach is something people agree on before I invest the time. Also note that It seems like there are no tests that ensure the block properties are called in the SessionDelegate yet.

**Comment by taquitos** [comment] 2016-04-04 19:52
Anyway we can discuss this suggestion?

**Comment by cnoon** [comment] 2016-04-07 06:49
Hi @taquitos, my apologies for not getting back to you sooner.

Your use case here is completely valid, and is definitely something that you can't do with the current implementation. Essentially you'd like to be able to proxy a `SessionDelegate` API or two somewhere to perform some additional operations, yet still be able to use the default logic. The problem is that you can't actually do this with the basic closures or even the closures with completion.

Now I'm not entirely sure I follow what you're attempting to do in your PR, but I do have a simple solution here. I have been debating this for quite some time, and I think it might just be time to do this. If we remove the `final` signature on the `SessionDelegate`, users are free to subclass the `SessionDelegate` and proxy the delegate APIs as much as necessary for the use case. Here's what that "could" look like:

```swift
public class SessionDelegate: 
    NSObject, 
    NSURLSessionDelegate, 
    NSURLSessionTaskDelegate, 
    NSURLSessionDataDelegate, 
    NSURLSessionDownloadDelegate 
{
    // All the current implementation...
}

public class CustomSessionDelegate: Manager.SessionDelegate {
    public override func URLSession(
        session: NSURLSession, 
        dataTask: NSURLSessionDataTask, 
        didReceiveData data: NSData) 
    {
        print("I received some data!")
        super.URLSession(session, dataTask: dataTask, didReceiveData: data)
    }
}
```

This would give a power user complete control over the process if they really needed. What I also like about this is that you can still use the more convenient override closures without having to subclass which is generally what you'd do in most cases. IMO, this seems like the best approach. Let's see if we can gather some feedback from some of the rest of the Alamofire team.

cc @jshier, @kcharwood, @kylef, @AnthonyMDev

**Comment by taquitos** [comment] 2016-04-07 15:30
I love this idea.

**Comment by AnthonyMDev** [comment] 2016-04-07 17:33
@cnoon I don't have any problem with this in general, but we did discuss something similar in #1099 and decided against it. These were your words:

> An alternative approach to this PR would be to remove the `final` modifier from the `SessionDelegate` declaration. This would allow users to subclass the `SessionDelegate` which would remove the need for these variant closures. I feel though that this is not a good idea since the `SessionDelegate` does not publicly expose the subdelegates and opening this up could lead to misuse when subclassing.

What "misuse" were you referring to here? I think we should consider that before making this change. 

Generally, I feel like this is an advanced use case, and anyone who needs to do this should be taking the responsibility to not misuse the subclass and dealing with any bugs that come of it. I think that there is a balance between making things simple for most users and protecting them from bugs and allowing the flexibility for advanced users to customize. This proposal seems to keep that balance intact to me.

**Comment by taquitos** [comment] 2016-04-08 15:29
I tend to agree, make things simple for normal users, but allow advanced use cases. Perhaps a good balance would be: remove final keyword from SessionDelegate, and add extra documentation and maybe an example of proper usage for advanced users in the documentation? I know we want to make it hard for people to do the wrong thing, but we also should balance that with enabling more advanced uses.

Another alternative approach could entail posting notifications for each delegate method call, and stuffing the same arguments into the userInfo object as the delegate methods. IMO this feels worse than removing "final" from the delegate, but we already have a few notifications for task lifecycle events.

**Comment by cnoon** [comment] 2016-04-09 23:01
The `misuse` I was referring to @AnthonyMDev was around the `subdelegates` and making sure they're still created and deallocated appropriately. I really hesitate to make them public. I just opened #1172 which should address all the concerns in this issue.

I'm going to close this issue out for now. Please direct all future comments to #1172.

**Closed by cnoon** 2016-04-09 23:01 UTC
Labels: feature request, help wanted, needs feedback, session delegate
