### ISSUE TITLE
App crash after download success but when move the file using moveItem with following message 'Terminated due to memory issue' 

### ISSUE THREAD

**Issue by suniljakhar** [Alamofire/Alamofire#1901] opened 2017-01-10 06:12 UTC
After updated the swift 3.0 of alamofire, we are start getting this issue. In previous versions of alamofire it is working fine. We have no clue on what charges are there in new moveItem method of swift 3.0. Please help us on that.

**Comment by jshier** [comment] 2017-01-10 20:48
Can you post the code that's causing the crash, along with the versions of Alamofire, Xcode, the operating systems you're seeing the crash on?

**Comment by suniljakhar** [comment] 2017-01-11 09:25
```javascript
self.request = self.backgroundManager!.download(data! as! URLConvertible, to: nil)
                .downloadProgress(queue: DispatchQueue.global(qos: .utility)) {  progress in
                    print("Progress: \(progress.fractionCompleted)")
                    DispatchQueue.main.async {
                        self.updateProgress(Int64(progress.fractionCompleted), totalBytesRead: progress.completedUnitCount, totalBytesExpectedToRead: progress.totalUnitCount)
                    }
                }
                .validate { request, response, temporaryURL, destinationURL in
                    // Custom evaluation closure now includes file URLs (allows you to parse out error messages if necessary)
                    return .success
                }
                .responseString {  response in
                    self.handleResponseOfDownload(response.response, error: response.result.error as NSError?)
            }
```

Alamofire Version - 4.2
Xcode - 8.1
iOS - 10.2

**Comment by pdfun** [comment] 2017-01-12 09:32
Have the same issue.   When finish download large file, move the file out of `Tmp`  directory will raise up the memory.Then the app will kill by system.

**Comment by suniljakhar** [comment] 2017-01-12 09:53
I tried this with sample of Alamofire also but end result is same.

**Comment by suniljakhar** [comment] 2017-01-17 06:35
Please help us to solve the issue ASAP.

**Comment by suniljakhar** [comment] 2017-01-17 06:47
@jshier 
Please look into it ASAP. We are urgently looking for solution.

**Comment by pdfun** [comment] 2017-01-17 06:53
@subicura `URLSessionDownloadTask` on this have't this problem. I have to use `URLSessionDownloadTask ` to instead.

**Comment by cnoon** [comment] 2017-01-17 17:00
@suniljakhar we need a working example here that demonstrates the issue in order to continue to investigate. I'm very doubtful here that the issue is Alamofire itself, however, I want to give you the opportunity here to have us help you investigate further. We just need to do your part and give us more to work with.

I'm going to leave this open for a few days for you to get us more info.

**Comment by suniljakhar** [comment] 2017-01-18 06:11
@cnoon You can use download example of Alamofire  with lower end device like 1GB RAM device with following url  http://mirror.nforce.com/pub/speedtests/500mb.bin or any other url of 1GB to reproduce issue.

I will try myself also but if you time please look into it.

**Comment by suniljakhar** [comment] 2017-01-18 10:43
@cnoon Here is my findings :- 
If we do not pass 'destination' in download statement,  like this ```Javascript Alamofire.download("http://mirror.nforce.com/pub/speedtests/100mb.bin", to: nil) ```Javascript
then it is working fine.
OR 
If we comment this line in code of downloadTaskDidFinishDownloadingToURL delegate of Alamofire 
   ```Javascript         // try FileManager.default.moveItem(at: location, to: destinationURL) ```Javascript
then is also working fine. So both are the same things, comment moveItem method or pass nil as destination, things are working fine.

But if we pass destination in download statement it sparks the memory footprint and crash the app on lower end devices.

So it seems that there is some problem with 'moveItem' methods of iOS SDK.

**Comment by suniljakhar** [comment] 2017-01-19 09:26
@cnoon  Before swift 3, moeItem method is working fine as expected.

**Comment by suniljakhar** [comment] 2017-01-19 13:08
@cnoon I have created one sample of URLSessionDownloadTask and there i use moeItem method and it is working fine as expected. So now it seems that there is some issue of threading or process that i m not able find-out in Alamofire. I tried to run `  try FileManager.default.moveItem(at: location, to: destinationURL)` in `DispatchQueue.main.sync` block but end result is still same.

**Comment by cnoon** [comment] 2017-01-19 17:03
What do you mean by you created a `URLSessionDownloadTask` and then you use `moveItem` and everything is working fine? Does that mean you created an example that doesn't use Alamofire and there are no memory constraint issues like you're seeing in Alamofire?

**Comment by suniljakhar** [comment] 2017-01-20 05:36
Yes

**Comment by cnoon** [comment] 2017-01-20 15:44
@jshier would you be able to investigate this issue to see what's going on?

**Comment by suniljakhar** [comment] 2017-01-21 05:01
@cnoon I am not able to find any thing related issue.

**Comment by suniljakhar** [comment] 2017-02-01 10:23
@cnoon  Any update on this.

**Comment by jshier** [comment] 2017-02-04 05:23
@suniljakhar I've created a test project using Xcode 8.2.1, Alamofire 4.3, and an iPhone 4S running iOS 9.3.5 (only other iOS device I have) and I can't reproduce your crash. I was able to successfully download a 1.4GB file on the device and move it to my documents folder. Please retest using the latest versions of Alamofire and Xcode. If you still get a crash, please post the crash log.

**Comment by jshier** [comment] 2017-02-19 22:36
@cnoon Only other thing I can think of is an iOS 10 issue, do you have an older iOS 10 compatible device to test with? I'm in the process of acquiring one but it'll be a week.

**Comment by cnoon** [comment] 2017-02-26 17:10
Hmmm...I might @jshier. Could you post your sample project here so I have it just incase? We could also just try the sample project on a newer device running iOS 10 and monitor the memory usage. It shouldn't have to crash for us to be able to detect a memory spike.

**Comment by jshier** [comment] 2017-02-26 23:23
Here's my test project, though it has a lot of different test bits, and my original download file was local, since the sites I found that do simple test file downloads were pretty slow. 

[AlamofireTest.zip](https://github.com/Alamofire/Alamofire/files/802400/AlamofireTest.zip)

**Comment by jshier** [comment] 2017-03-20 02:03
@suniljakhar I've run my test project on an iPhone 5s running iOS 10.2.1 and it worked without issue. I'm closing this issue, as we can't reproduce it. If you come up with a test project that reliably reproduces the issue, let us know.

**Closed by jshier** 2017-03-20 02:03 UTC
Labels: bug, download request, needs feedback, needs investigation

**Comment by proth** [comment] 2018-03-05 09:14
I've had the same issue and it turned out that [netfox](https://github.com/kasketis/netfox) was the cause. It seems like it's trying to keep the entire response in memory which leads to memory pressure and an app termination.
