### ISSUE TITLE
Alamofire (5.4.4) -> org.alamofire.session.rootQueue

### ISSUE THREAD

**Issue by johannes-codes** [Alamofire/Alamofire#3515] opened 2021-11-03 16:34 UTC
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

We updated several Pods, including Alamofire, in our last release. We went from 5.4.3 to 5.4.4 and experienced by today 525 crash events affecting 432 users. All crashes have the same signature and happen across multiple OSs as well as device types.

## What did you expect to happen?

To have a seamless switch from `Alamofire (5.4.3)` -> `Alamofire (5.4.4)`

## What happened instead?

**Hundreds** of our users crashed with the same cause `Crashed: org.alamofire.session.rootQueue`.

## Alamofire Environment

**Alamofire Version: 5.4.4**
**Dependency Manager: Cocoapods**
**Xcode Version: 12.4 (12D4e) & 13.0 (13A233)**
**Swift Version: Swift 5**
**Platform(s) Running Alamofire: iOS**
**macOS Version Running Xcode: macOS Big Sur 11.6 and others**

## Demo Project

We can so far not reproduce the issue. We have analyzed it with TSan but without any luck.

![image](https://user-images.githubusercontent.com/18604283/140102734-df4eb628-2fd9-45e4-a36a-b6c4441505e5.png)

Example Stacktrace:
```
Crashed: org.alamofire.session.rootQueue
0  CoreFoundation                 0x6b5dc CFDictionaryGetValue + 100
1  Foundation                     0x108c94 _NSSetLongLongValueAndNotify + 92
2  CFNetwork                      0x1da35c _CFNetworkHTTPConnectionCacheSetLimit + 152148
3  Foundation                     0x132f88 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
4  Foundation                     0x20628 -[NSBlockOperation main] + 104
5  Foundation                     0x1353b0 __NSOPERATION_IS_INVOKING_MAIN__ + 24
6  Foundation                     0x202b0 -[NSOperation start] + 808
7  Foundation                     0x135e54 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
8  Foundation                     0x1358e0 __NSOQSchedule_f + 184
9  libdispatch.dylib              0x13484 _dispatch_block_async_invoke2 + 148
10 libdispatch.dylib              0x481c _dispatch_client_callout + 20
11 libdispatch.dylib              0xc004 _dispatch_lane_serial_drain + 620
12 libdispatch.dylib              0xcc00 _dispatch_lane_invoke + 404
13 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread + 764
14 libsystem_pthread.dylib        0x37a4 _pthread_wqthread + 276
15 libsystem_pthread.dylib        0xa74c start_wqthread + 8
```

**Comment by johannes-codes** [comment] 2021-11-03 16:36
I know that this issue has been posted by others before. I just want to make sure, that I've done my best to give you guys feedback as well as gain some insights on the cause of this.

Our plan, for now, will be, to roll back to Alamofire (5.4.3) and wait until we either get feedback on this issue or another version is released.

**Comment by jshier** [comment] 2021-11-03 17:05
Aside from it happening on Alamofire's queue, this doesn't seem to be our issue. There's nothing in 5.4.4 that would cause this, so this is most likely the intersection of several updated dependencies with an updated build. This crash stack is very similar to one caused by a Firebase Performance KVO bug, so I would take a look at any automatic analytics or performance tracking frameworks you have and see if you integrate them manually rather than having them swizzle into or observe ongoing network activity. Many of those frameworks like to inject themselves into the `URLSessionDelegate` and perform work on its queue, which is our `rootQueue`. It would be strange if, keeping everything else updated, rolling back to 5.4.3 helped anything, but keep us appraised.

**Comment by johannes-codes** [comment] 2021-11-03 17:26
Thank you for the quick reply. We did actually also update several Firebase frameworks, including Analytics. I also saw the mentioned Firebase/Performance issue - but we do not directly include Performance as pod. That does not mean, it's not related to Performance under the hood - but at least it's not as obvious. I'll keep you posted on my further investigations and finding 🥲

**Comment by jshier** [comment] 2021-11-22 17:21
Looks like a rollback of the Firebase updates fixed the issue, so I'm closing this.

**Closed by jshier** 2021-11-22 17:21 UTC
Labels: needs investigation
