### ISSUE TITLE
I Use Alamofire, add Proxy, but always show me error is "FAILURE: Error Domain=NSURLErrorDomain Code=-999 "cancelled""

### ISSUE THREAD

**Issue by karepbq** [Alamofire/Alamofire#2528] opened 2018-05-23 01:43 UTC
> static var requestManager = Alamofire.SessionManager()
let cfg = Alamofire.SessionManager.default.session.configuration
        cfg.connectionProxyDictionary = [
            kCFNetworkProxiesHTTPEnable: true,
            kCFNetworkProxiesHTTPPort: 80,
            kCFNetworkProxiesHTTPProxy: ip
        ]
        
        requestManager = Alamofire.SessionManager(configuration: cfg)
        requestManager.request(...)

**Comment by jshier** [comment] 2018-05-23 01:45
Error code -999 is nearly always caused by the `SessionManager` going out of scope and being deinit'd. From your brief code same, that seems to be what's happening here. I suggest you keep a reference to your `SessionManager` somewhere. I usually use a singleton.

In the future, please fill out the issue template when creating an issue. Thanks!

**Closed by jshier** 2018-05-23 01:45 UTC
