### ISSUE TITLE
When is the documentation of Alamofire 5 open?

### ISSUE THREAD

**Issue by LGCooci** [Alamofire/Alamofire#2853] opened 2019-06-24 05:51 UTC
May I venture to ask When is the documentation of Alamofire 5 open? I need it very much

**Comment by WGFcode** [comment] 2019-06-24 11:32
Was rejected when I uploaded the app to the app store. The cause of the error is “This bundle is invalid. The value for key CFBundleShortVersionString '5.0.0.beta.5' in the Info.plist file must be a period-separated list of at most three non-negative integers”。How should I handle this?

**Comment by tirrorex** [comment] 2019-06-24 12:47
Hum this is a serious issue indeed.
@WGFcode do you use alamofire as a first level dependency or is it a dependency of a library you're using? (like alamofireobjectmapper for example).

**Comment by WGFcode** [comment] 2019-06-24 13:12
@tirrorex Dependent as the first season. The problem has been fixed: modify github "Alamofire/Alamofire" "5.0.0-beta.5" in the Cartfile to github "Alamofire/Alamofire" by default is the version of Alamofire 4.8.x. But you need to modify some of the network related code.

**Comment by tirrorex** [comment] 2019-06-24 13:19
Great, thought there was a regression or something :)

**Comment by cnoon** [comment] 2019-06-24 16:02
@WGFcode that issue was resolved in beta 6 in https://github.com/Alamofire/Alamofire/pull/2808. If you update, your issue should be resolved.

**Comment by jshier** [comment] 2019-06-26 16:05
@LGCooci #2845 will complete our API documentation and we're working on our usage guides right now. In the mean time, feel free to ask any questions on our [Swift Forum](https://forums.swift.org/c/related-projects/alamofire).

**Closed by jshier** 2019-06-26 16:05 UTC
