### ISSUE TITLE
How to send in multipartFormData array?

### ISSUE THREAD

**Issue by kshysius** [Alamofire/Alamofire#1327] opened 2016-06-30 22:30 UTC
Hi, i need send array like this in multipartFormData

my array: 

["t": "aa", 
 "t2": 0, 
 "t3": {
  "t3_2" = EHU123;
}]

t3 array in array how send this with multipartFormData?

**Comment by adrianbrink** [comment] 2016-07-25 08:12
Possible duplicate of #1309 .

Tag: Help wanted.

**Comment by tobiasoleary** [comment] 2016-09-07 14:37
As far implementation are you thinking about how Ruby on Rails implements building forms for sending hierarchical data? http://guides.rubyonrails.org/form_helpers.html

**Comment by cnoon** [comment] 2016-09-10 10:43
Hi @kshysius,

You'll need to encode the array (that's actually a dictionary by the way) into whatever data format you wish to add into the multipart form data object. I'd recommend using JSON if you don't know what to use. Your platform team should be able to tell you what they expect. Anyways, once you have it encoded into a data object, you can then use the `appendBodyPart(data:name:)` API.

Cheers. 🍻

**Closed by cnoon** 2016-09-10 10:43 UTC

**Comment by rajtharan-g** [comment] 2018-02-05 11:07
Hi, Im not able to send data as an array using multipart.
How would I send the parameters using multipart if I have the value as an array and I want to send the params as below

“phone_numbers” : [
					[“id”: 1, “number”: “1234567890”],
					[“id”: 2, “number”: “0987654321”]
				   ]

Even If I try to convert string array into data and send it, then the params is sent as a string instead of array type.

**Comment by basilmariano** [comment] 2018-11-19 12:19
Hi, 
Im experiencing the same issue here. i was trying to send a paramater like this in Multipart request

`{
	"user_email":"sample_email.com",
	"user_token":"yiDmaVs6Ax-zUj1cM-Eh",
	"witness":{
		"name":"Charlie Wiwoo",
		"contact_no": "0912382232",
		"email":"charliewiwoo@sample.com",
		"claim_id":6
	}
}`

I request like like this

`sessionManager.upload(multipartFormData: { (multipartFormData) in
                for (key, value) in parameters {
                    
                    if let _ = value as? Parameters {
                        if let jsonData = try? JSONSerialization.data(withJSONObject: value, options:[]) {
                            multipartFormData.append(jsonData, withName: key as String)
                        }
                    } else {
                        multipartFormData.append("\(value)".data(using: String.Encoding.utf8)!, withName: key as String)
                    }
                    
                }
                
                multipartFormData.append(imageData, withName: "witness_photo", fileName: "image.png", mimeType: "image/png")
            }, usingThreshold: UInt64.init(), with: request) { [weak self] (result) in
                
                guard let strongSelf = self else { return }
                
                switch result{
                case .success(let upload, _, _):
                    upload.responseJSON { response in
                        print("Succesfully uploaded")
                        if let err = response.error{
                            let apiError = strongSelf.getFailureError(err)
                            completion(apiError)
                            return
                        }
                        completion(nil)
                    }
                case .failure(let error):
                    print("Error in upload: \(error.localizedDescription)")
                    let apiError = strongSelf.getFailureError(error)
                    completion(apiError)
                }
            }`

**Comment by gleutar** [comment] 2020-01-30 16:14
Hi @basilmariano  did you ever solve your issue from above? I'm now having the same problem. My inner array has booleans and integers. It's a [String : Any] array.

**Comment by panfilo-dengun** [comment] 2020-01-31 04:23
Hi i checked if the value from the dictionary is another dictionary and if true, iterate it and get all keys and values


```
let request = API.baseURL +  "/companies"
            sessionManager.upload(multipartFormData: { (multipartFormData) in
                for (key, value) in params {
                    if let val = value as? Parameters {
                        for (key1, value) in val {
                            multipartFormData.append("\(value)".data(using: String.Encoding.utf8)!, withName: "\(key)[\(key1)]" as String)
                        }
                        multipartFormData.append(UIImageJPEGRepresentation(image, 0.5)!, withName: "\(key)[logo]", fileName: "company-logo.jpeg", mimeType: "image/jpeg")
                    } else {
                        multipartFormData.append("\(value)".data(using: String.Encoding.utf8)!, withName: key as String)
                    }
                }
            }, usingThreshold: UInt64.init(), to: request, method: .post, headers: nil) { (result) in
                switch result {
                case .success(let upload, _, _):
                    upload.responseJSON { response in
                        debugPrint(response)
                        completion(true, "")
                    }
                case .failure(let encodingError):
                    print(encodingError)
                    completion(false, encodingError.localizedDescription)
                }
            }
```

**Comment by gleutar** [comment] 2020-02-03 07:19
Hi @panfilo-dengun ! Thanks for this!

**Comment by RishabhSRS** [comment] 2020-05-27 12:06
> Hi, Im not able to send data as an array using multipart.
> How would I send the parameters using multipart if I have the value as an array. For eg:, I want to send phone number array inside a user object like below.
> 
> "user": ["id": 123,
> "phone_numbers” : [
> [“id”: 1, “number”: “1234567890”],
> [“id”: 2, “number”: “0987654321”]
> ],
> "name": "xyz"]
> 
> Even If I try to convert string array into data and send it, then the params is sent as a string including some escape sequence instead of array like below.
> 
> "user": ["id": 123,
> ”phone_numbers": "[
> [\"number\": \"8883975490", \"id\": 1],
> [\"number\": \"9500243960\", \"id\": 15]
> ]",
> "name": "xyz"]
> 
> Please do suggest any solution for the above said issue.

Any Solution?
