### ISSUE TITLE
SessionManager.swift DispatchQueue

### ISSUE THREAD

**Issue by NVAT** [Alamofire/Alamofire#1741] opened 2016-10-30 13:31 UTC
Hi when I have updated xcode 8.1 and got exception 
//  SessionManager.swift line 152
 let queue = DispatchQueue(label: "org.alamofire.session-manager." + UUID().uuidString) 
bad access

**Comment by stingwear** [comment] 2016-11-01 13:04
Hi, I have the same exception and I can't release the new version of my app until this issue be fixed. How can I help you to solve this?
Thks

**Comment by csurbier** [comment] 2016-11-01 16:50
Hi,

Same for me since i have updated to Xcode 8.1

**Comment by acehanilker** [comment] 2016-11-03 02:24
Hi, I have the same exception

**Comment by acehanilker** [comment] 2016-11-07 00:53
i don't know why but when copy workspace into another folder and work form this place everything is fine. i dont have same exception. but when try to work in from old folder it has exception 🤔😳

**Comment by jshier** [comment] 2016-11-13 00:01
We're not seeing this issue anywhere. From the linked SwiftyDropbox report, it looks like the crash is actually occurring in `DispatchQueue`'s `init` method, with some sort of `objc_msgSend`. We'll investigate.

**Comment by cnoon** [comment] 2016-11-13 00:34
This is not something we've been able to reproduce on our end with our Alamofire sample app running iOS 10.1.1 on device against Xcode 8.1 in a release build. At this point, we're going to need someone to post up a sample project that demonstrates the issue since there's nothing else we can do here. We can't reproduce the issue no matter how hard we try.

I'm going to close this issue out for now. If someone can post more information or a sample project, we'll happily re-open and investigate further.

Cheers. 🍻

**Closed by cnoon** 2016-11-13 00:34 UTC
Labels: needs investigation, swift
