### ISSUE TITLE
The resumeData always returns nil if the download request is interrupted.

### ISSUE THREAD

**Issue by tsuiyuenhong** [Alamofire/Alamofire#3416] opened 2021-03-02 03:05 UTC
This bug may be introduced from Alamofire 5 because resume data was not updated when the download request was interrupted.

Need to get `NSURLSessionDownloadTaskResumeData` from the `error.userInfo`.

**Comment by jshier** [comment] 2021-03-02 03:17
This is not a bug but an intentional design choice. You can access the error in the response handler and gain access to the resume data that way.

**Comment by jshier** [comment] 2021-03-02 03:42
On second thought you may be right. This needs more investigation.

**Comment by tsuiyuenhong** [comment] 2021-03-02 03:51
Thanks for the reply, looking forward to the investigation result.

**Comment by jshier** [comment] 2021-03-07 02:37
Looks like I'll be able to test this, so I've added support on the `feature/error-resumedata` branch. Feel free to give it a try. I'll be integrating tests later.

**Comment by jshier** [comment] 2021-03-08 04:14
This has been addressed in #3419 and will go out with the next release.

**Closed by jshier** 2021-03-08 04:14 UTC
Labels: needs investigation

**Comment by jshier** [comment] 2021-04-03 21:59
This has been released as part of 5.4.2.
