### ISSUE TITLE
Alamofire 3.5.1 request!.cancel() resume data is nil in response block 

### ISSUE THREAD

**Issue by gaoshanyu** [Alamofire/Alamofire#1807] opened 2016-11-27 06:42 UTC
I'm develop in swift2.3, the response resume data is nil when I send request!.cancel(). The request code as below:
```
request = Alamofire
            .download(.GET, downloadFile.url, destination: { [unowned self](url, response) -> NSURL in
                
                return NSURL(fileURLWithPath: self.filePath)
                
                })
            .progress { [unowned self](bytesRead, totalBytesRead, totalBytesExpectedToRead) in
                
                self.readedBytes = totalBytesRead
                
                dispatch_async(dispatch_get_main_queue()) {
                    let buffer = ["file": Int64(self.downloadFile.id), "speed": bytesRead, "readed": totalBytesRead, "all": totalBytesExpectedToRead]
                    GlobalBroadcast_Inst.broadcastMsg(.downloading, msg: buffer)
                }
            }
            .response { [unowned self](request, response, data, error) in
                
                if let error = error {
                    if error.code == NSURLErrorCancelled {
                        debugPrint("Canceled download: request \(request), response \(response), data \(data), error \(error)")
                    } else {
                        debugPrint(error)
                    }
                    
                } else {
                    
                    debugPrint("Downloaded file successfully")
                }
        }
```

The cancel response debug print:
```
"Canceled download: 
request Optional(<NSMutableURLRequest: 0x7f85c9911370> {
 URL: http://211.95.70.126:8080/qjbim-file/upload/44/public/002/2016/11/26/7dd46451-00f6-46cd-8abd-2c7f3378691f.png 
}), 
response Optional(<NSHTTPURLResponse: 0x7f85c76a6eb0> { 
URL: http://211.95.70.126:8080/qjbim-file/upload/44/public/002/2016/11/26/7dd46451-00f6-46cd-8abd-2c7f3378691f.png
 } { 
status code: 200, headers {\n    
\"Accept-Ranges\" = bytes;\n    
\"Content-Disposition\" = \"attachment; filename=2015-09-03 040227.png\";\n    
\"Content-Length\" = 7063823;\n   
 \"Content-Range\" = \"bytes 0-7063822/7063823\";\n    
\"Content-Type\" = png;\n    
Date = \"Sun, 27 Nov 2016 06:02:53 GMT\";\n    
Server = \"Apache-Coyote/1.1\";\n} 
}), 
data nil, 
error Error Domain=NSURLErrorDomain Code=-999 \"cancelled\" UserInfo={
NSErrorFailingURLKey=http://211.95.70.126:8080/qjbim-file/upload/44/public/002/2016/11/26/7dd46451-00f6-46cd-8abd-2c7f3378691f.png, NSLocalizedDescription=cancelled, 
NSErrorFailingURLStringKey=http://211.95.70.126:8080/qjbim-file/upload/44/public/002/2016/11/26/7dd46451-00f6-46cd-8abd-2c7f3378691f.png
}"
```

**Comment by jshier** [comment] 2016-11-29 04:08
We'd need more code context to be sure, but unexpected cancellation is usually caused by your manager going out of scope and being deallocated, causing any active requests to be cancelled. However, that doesn't appear to the the case here. Without more context it's hard to be sure.

**Comment by gaoshanyu** [comment] 2016-12-03 05:21
@jshier Hi thanks for your reply. I place all the Uploader code here for you refer:
```
import Foundation
import Alamofire

public struct UploadFile {
    var id: String!
    var name: String!
    var data: AnyObject!
    var size: Int!
    var directoryID: Int!
    var status: UploadStatus = UploadStatus.waitting
    var createAt: NSDate = NSDate()
}

public class Uploader: NSObject {

    private var uploadFile: UploadFile!
    
    private(set) public var uploading = false
    
    private var request: Request?
    
    // singleton
    
    public class var sharedInstance: Uploader {
        struct Statics {
            static var instance = Uploader()
        }
        return Statics.instance
    }
    
    override init() {
        super.init()
    }
    
    public func upload(file: UploadFile) {
        uploadFile = file
        upload()
    }
    
    public func cancel(file: UploadFile) {
        if file.id == uploadFile.id, let _ = request {
            self.request?.cancel()
        }
    }
}

extension Uploader {
    
    func upload() {
        
        uploading = true
        
        let parameters = [
            "projectId":"\(UserManager_Inst.projectId)",
            "groupId":"\(UserManager_Inst.groupId)",
            "tokenId":UserManager_Inst.tokenID,
            "parentDirId":"\(uploadFile.directoryID)"
        ]
        Alamofire.upload(
            .POST,
            "\(AppManager_Inst.currentServerAddress)/cloud/uploadFile",
            multipartFormData: { [unowned self] multipartFormData in
                
                if self.uploadFile.data.isKindOfClass(UIImage),
                    let image = self.uploadFile.data as? UIImage,
                    let imageData = UIImagePNGRepresentation(image) {
                    multipartFormData.appendBodyPart(data: imageData, name: "file", fileName: "\(self.uploadFile.name).png", mimeType: "image/png")
                } else {
                    GlobalBroadcast_Inst.broadcastMsg(.uploadError, msg: ["file": "\(self.uploadFile.id)", "code": "\(UploadError.fileError.rawValue)"])
                }
                
                for (key, value) in parameters {
                    multipartFormData.appendBodyPart(data: value.dataUsingEncoding(NSUTF8StringEncoding)!, name: key)
                }
                
            }, encodingCompletion: { [unowned self] encodingResult in
                switch encodingResult {
                case .Success(let upload, _, _):
                    
                    self.request = upload
                    upload.progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
                        dispatch_async(dispatch_get_main_queue()) {
                            let buffer = ["file": "\(self.uploadFile.id)", "speed": "\(bytesRead)", "readed": "\(totalBytesRead)", "all": "\(totalBytesExpectedToRead)"]
                            GlobalBroadcast_Inst.broadcastMsg(.uploading, msg: buffer)
                        }
                    }
                    upload.responseData(completionHandler: { (response) in
                        
                        self.uploading = false
                        
                        let resp = NewFileResp.parseFromData(response.data!)
                        if resp.responseInfo.responseCode == ResponseCode.Succeed.rawValue {
                            
                            GlobalBroadcast_Inst.broadcastMsg(.uploadError, msg: ["file": "\(self.uploadFile.id)", "code": "\(UploadError.success.rawValue)"])
                            
                        } else {
                            GlobalBroadcast_Inst.broadcastMsg(.uploadError, msg: ["file": "\(self.uploadFile.id)", "code": "\(UploadError.failed.rawValue)"])
                        }
                    })
                    
                case .Failure(let error):
                    self.uploading = false
                    GlobalBroadcast_Inst.broadcastMsg(.uploadError, msg: ["file": "\(self.uploadFile.id)", "code": "\(UploadError.networkError.rawValue)"])
                    print(error)
                }
            }
        )
    }
}

```

I use it as a singleton object in my project and it should alive in the full lifecycle of my app.

**Comment by cnoon** [comment] 2016-12-16 23:39
Hi @gaoshanyu,

I think you're misunderstanding how cancellation and resumeData work together. Just because you cancel a request does not mean that `resumeData` will be generated. It is only generated if iOS is at a point where the resume data can actually be generated. For example, if the request hasn't received a response and started receiving the stream of data, then iOS won't generate resume data for the request.

In these cases, you need to hold onto the resume data if it was generated, or simply restart the entire request if it doesn't exist.

Hopefully that helps clarify things.

Cheers. 🍻

**Closed by cnoon** 2016-12-16 23:39 UTC
Labels: needs feedback

**Comment by gaoshanyu** [comment] 2017-01-08 07:19
@cnoon It's my mistake. The response.data is 0 bytes when I do upload.cancel(), sorry for trouble you guys.
