### ISSUE TITLE
Alamofire crash on iOS 13.3.1

### ISSUE THREAD

**Issue by foxfire881** [Alamofire/Alamofire#3082] opened 2020-02-25 15:03 UTC
MacOS Catalina 10.15.3 + XCode 11.3.1 + iOS 13.3.1

my app works well on iOS 13.3, but after I upgrade my iPhone Xs Max to iOS13.3.1 yesterday, it crashed(but still works well in simulators), it seems there are some bugs of Alamofire. pls fix it. thank you~

console errors:
---------------------------------------------------------
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Punch
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire'

	/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire: stat() failed with errno=25
	/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire'

	/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire: stat() failed with errno=1
	/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire'

	/private/var/containers/Bundle/Application/FC18E950-4825-4C5E-96E5-3E0C41D0D0A9/Punch.app/Frameworks/Alamofire.framework/Alamofire: stat() failed with errno=1
(lldb)

**Comment by jshier** [comment] 2020-02-25 15:08
This is a duplicate of #3069.

**Closed by jshier** 2020-02-25 15:08 UTC
