### ISSUE TITLE
Crashed: org.alamofire.session.rootQueue EXC_BAD_ACCESS KERN_INVALID_ADDRESS NSKeyValueWillChange

### ISSUE THREAD

**Issue by SherifKamalSalem** [Alamofire/Alamofire#3333] opened 2020-10-21 11:56 UTC
Crashed: org.alamofire.session.rootQueue
0  libobjc.A.dylib                0x1bcee8ca0 objc_retain + 16
1  Foundation                     0x1aa91f1bc NSKeyValueWillChange + 400
2  Foundation                     0x1aa91ee9c -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 424
3  Foundation                     0x1aa863800 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 68
4  Foundation                     0x1aa91a3d8 _NSSetLongLongValueAndNotify + 284
5  CFNetwork                      0x1a9e3d074 _CFNetworkHTTPConnectionCacheSetLimit + 153068
6  Foundation                     0x1aa941cc8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
7  Foundation                     0x1aa83eb18 -[NSBlockOperation main] + 100
8  Foundation                     0x1aa943f80 __NSOPERATION_IS_INVOKING_MAIN__ + 20
9  Foundation                     0x1aa83e7d4 -[NSOperation start] + 784
10 Foundation                     0x1aa944978 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
11 Foundation                     0x1aa944444 __NSOQSchedule_f + 180
12 libdispatch.dylib              0x1a92c0cb8 _dispatch_block_async_invoke2 + 104
13 libdispatch.dylib              0x1a92de280 _dispatch_client_callout + 16
14 libdispatch.dylib              0x1a92ba4fc _dispatch_lane_serial_drain$VARIANT$armv81 + 568
15 libdispatch.dylib              0x1a92bafe8 _dispatch_lane_invoke$VARIANT$armv81 + 404
16 libdispatch.dylib              0x1a92c4808 _dispatch_workloop_worker_thread + 692
17 libsystem_pthread.dylib        0x1eef885a4 _pthread_wqthread + 272
18 libsystem_pthread.dylib        0x1eef8b874 start_wqthread + 8

**Comment by cristianespes** [comment] 2020-10-21 13:40
Version?

**Comment by jshier** [comment] 2020-10-21 14:23
This is a duplicate of #3326.

**Closed by jshier** 2020-10-21 14:23 UTC
